// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 初始化 Rust 书源引擎
void initEngine() => LegadoEngine.instance.api.crateApiInitEngine();

/// 引擎版本号
String engineVersion() => LegadoEngine.instance.api.crateApiEngineVersion();

/// 搜索书籍
Future<List<SearchItem>> search({
  required String sourceJson,
  required String keyword,
}) => LegadoEngine.instance.api.crateApiSearch(
  sourceJson: sourceJson,
  keyword: keyword,
);

/// 发现页 / 分类页
Future<List<SearchItem>> explore({
  required String sourceJson,
  required String exploreUrl,
  required int page,
}) => LegadoEngine.instance.api.crateApiExplore(
  sourceJson: sourceJson,
  exploreUrl: exploreUrl,
  page: page,
);

/// 获取书籍详情
Future<BookInfoItem> getBookInfo({
  required String sourceJson,
  required String bookUrl,
}) => LegadoEngine.instance.api.crateApiGetBookInfo(
  sourceJson: sourceJson,
  bookUrl: bookUrl,
);

/// 获取目录
Future<List<ChapterItem>> getToc({
  required String sourceJson,
  required String bookUrl,
}) => LegadoEngine.instance.api.crateApiGetToc(
  sourceJson: sourceJson,
  bookUrl: bookUrl,
);

/// 获取章节正文
Future<String> getContent({
  required String sourceJson,
  required String chapterUrl,
}) => LegadoEngine.instance.api.crateApiGetContent(
  sourceJson: sourceJson,
  chapterUrl: chapterUrl,
);

/// 书源校验（搜索 / 发现 / 目录 / 正文）
Future<SourceValidation> validateSource({
  required String sourceJson,
  required String keyword,
}) => LegadoEngine.instance.api.crateApiValidateSource(
  sourceJson: sourceJson,
  keyword: keyword,
);

/// 分步调试搜索
Future<DebugResult> debugSearch({
  required String sourceJson,
  required String keyword,
}) => LegadoEngine.instance.api.crateApiDebugSearch(
  sourceJson: sourceJson,
  keyword: keyword,
);

/// 分步调试目录
Future<DebugResult> debugToc({
  required String sourceJson,
  required String bookUrl,
}) => LegadoEngine.instance.api.crateApiDebugToc(
  sourceJson: sourceJson,
  bookUrl: bookUrl,
);

/// 启动 Web API 服务
Future<WebApiStatus> startWebApi({required int port, required String token}) =>
    LegadoEngine.instance.api.crateApiStartWebApi(port: port, token: token);

/// 停止 Web API 服务
Future<void> stopWebApi() => LegadoEngine.instance.api.crateApiStopWebApi();

/// Web API 运行状态
WebApiStatus webApiStatus() => LegadoEngine.instance.api.crateApiWebApiStatus();

/// TXT 分章
List<LocalChapterItem> parseTxtChapters({required String content}) =>
    LegadoEngine.instance.api.crateApiParseTxtChapters(content: content);

/// EPUB 解析
LocalBookInfo parseEpub({required List<int> data}) =>
    LegadoEngine.instance.api.crateApiParseEpub(data: data);

/// 记录阅读（按书 + 日期累加）
void recordReading({
  required String bookId,
  required String bookName,
  required int chars,
  required int durationSeconds,
}) => LegadoEngine.instance.api.crateApiRecordReading(
  bookId: bookId,
  bookName: bookName,
  chars: chars,
  durationSeconds: durationSeconds,
);

/// 阅读统计（range: week / month / year）
ReadingStats getReadingStats({required String range}) =>
    LegadoEngine.instance.api.crateApiGetReadingStats(range: range);

/// 导出阅读记录（csv / json）
String exportReadingRecords({required String format}) =>
    LegadoEngine.instance.api.crateApiExportReadingRecords(format: format);

/// 写入详细阅读会话
void recordDetailedReadSession({
  required String bookName,
  required PlatformInt64 startTime,
  required PlatformInt64 endTime,
  required PlatformInt64 readIteration,
}) => LegadoEngine.instance.api.crateApiRecordDetailedReadSession(
  bookName: bookName,
  startTime: startTime,
  endTime: endTime,
  readIteration: readIteration,
);

/// 导出详细阅读会话
String exportDetailedReadRecords() =>
    LegadoEngine.instance.api.crateApiExportDetailedReadRecords();

/// 单本书阅读统计（阅读小票）
BookReadingStats getBookReadingStats({required String bookId}) =>
    LegadoEngine.instance.api.crateApiGetBookReadingStats(bookId: bookId);

/// 保存想法笔记
void upsertNote({
  required String id,
  required String bookId,
  required String chapterTitle,
  required String selectedText,
  required String noteContent,
  required int position,
  required int chapterPos,
}) => LegadoEngine.instance.api.crateApiUpsertNote(
  id: id,
  bookId: bookId,
  chapterTitle: chapterTitle,
  selectedText: selectedText,
  noteContent: noteContent,
  position: position,
  chapterPos: chapterPos,
);

/// 删除想法笔记
void deleteNote({required String id}) =>
    LegadoEngine.instance.api.crateApiDeleteNote(id: id);

/// 列出想法笔记（book_id 为空则全部）
List<NoteDto> listNotes({required String bookId}) =>
    LegadoEngine.instance.api.crateApiListNotes(bookId: bookId);

/// 导出 Obsidian 风格 Markdown
String exportNotesMarkdown({required String bookId}) =>
    LegadoEngine.instance.api.crateApiExportNotesMarkdown(bookId: bookId);

/// 保存独立书签；time 对齐原版 Bookmark 主键
void upsertBookmark({
  required PlatformInt64 time,
  required String bookId,
  required String bookName,
  required String bookAuthor,
  required int chapterIndex,
  required int chapterPos,
  required String chapterName,
  required String bookText,
  required String content,
}) => LegadoEngine.instance.api.crateApiUpsertBookmark(
  time: time,
  bookId: bookId,
  bookName: bookName,
  bookAuthor: bookAuthor,
  chapterIndex: chapterIndex,
  chapterPos: chapterPos,
  chapterName: chapterName,
  bookText: bookText,
  content: content,
);

/// 删除独立书签
void deleteBookmark({required PlatformInt64 time}) =>
    LegadoEngine.instance.api.crateApiDeleteBookmark(time: time);

/// 列出独立书签；book_id 为空则全部
List<BookmarkDto> listBookmarks({required String bookId}) =>
    LegadoEngine.instance.api.crateApiListBookmarks(bookId: bookId);

/// 执行裸 JS（登录 UI / loginUrl / 按钮脚本）
String evalJs({
  required String script,
  required String jsLib,
  required String baseUrl,
}) => LegadoEngine.instance.api.crateApiEvalJs(
  script: script,
  jsLib: jsLib,
  baseUrl: baseUrl,
);

/// 预热 Rust 登录头缓存（Dart SharedPreferences → 引擎）
void seedLoginHeader({required String sourceUrl, required String header}) =>
    LegadoEngine.instance.api.crateApiSeedLoginHeader(
      sourceUrl: sourceUrl,
      header: header,
    );

/// 取出 loginCheckJs 新写入的登录头（JSON: url → header），供 Dart 回写 prefs
String drainLoginHeaderUpdates() =>
    LegadoEngine.instance.api.crateApiDrainLoginHeaderUpdates();

/// 获取 RSS 文章列表 — 对齐 Jingshiro Rss.getArticlesAwait
Future<RssArticlesResult> getRssArticles({
  required String sourceJson,
  required String sortUrl,
  required String sortName,
  required int page,
}) => LegadoEngine.instance.api.crateApiGetRssArticles(
  sourceJson: sourceJson,
  sortUrl: sortUrl,
  sortName: sortName,
  page: page,
);

/// 获取 RSS 正文 — 对齐 Jingshiro Rss.getContentAwait
Future<String> getRssContent({
  required String sourceJson,
  required String articleLink,
}) => LegadoEngine.instance.api.crateApiGetRssContent(
  sourceJson: sourceJson,
  articleLink: articleLink,
);

/// HTTP 请求并返回解码后的文本（调试用）
Future<String> httpFetch({
  required String url,
  required String method,
  String? body,
  required String charset,
  String? referer,
  String? sourceUrl,
  String? concurrentRate,
}) => LegadoEngine.instance.api.crateApiHttpFetch(
  url: url,
  method: method,
  body: body,
  charset: charset,
  referer: referer,
  sourceUrl: sourceUrl,
  concurrentRate: concurrentRate,
);

/// 书籍详情
class BookInfoItem {
  final String name;
  final String author;
  final String coverUrl;
  final String intro;
  final String kind;
  final String lastChapter;
  final String tocUrl;

  const BookInfoItem({
    required this.name,
    required this.author,
    required this.coverUrl,
    required this.intro,
    required this.kind,
    required this.lastChapter,
    required this.tocUrl,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      intro.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      tocUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfoItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          intro == other.intro &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          tocUrl == other.tocUrl;
}

/// 单本书阅读统计
class BookReadingStats {
  final int durationSeconds;
  final int readChars;
  final String? startDate;
  final String? lastDate;
  final int readingDays;

  const BookReadingStats({
    required this.durationSeconds,
    required this.readChars,
    this.startDate,
    this.lastDate,
    required this.readingDays,
  });

  @override
  int get hashCode =>
      durationSeconds.hashCode ^
      readChars.hashCode ^
      startDate.hashCode ^
      lastDate.hashCode ^
      readingDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookReadingStats &&
          runtimeType == other.runtimeType &&
          durationSeconds == other.durationSeconds &&
          readChars == other.readChars &&
          startDate == other.startDate &&
          lastDate == other.lastDate &&
          readingDays == other.readingDays;
}

/// 独立书签实体；字段对齐 Jingshiro Bookmark
class BookmarkDto {
  final PlatformInt64 time;
  final String bookId;
  final String bookName;
  final String bookAuthor;
  final int chapterIndex;
  final int chapterPos;
  final String chapterName;
  final String bookText;
  final String content;

  const BookmarkDto({
    required this.time,
    required this.bookId,
    required this.bookName,
    required this.bookAuthor,
    required this.chapterIndex,
    required this.chapterPos,
    required this.chapterName,
    required this.bookText,
    required this.content,
  });

  @override
  int get hashCode =>
      time.hashCode ^
      bookId.hashCode ^
      bookName.hashCode ^
      bookAuthor.hashCode ^
      chapterIndex.hashCode ^
      chapterPos.hashCode ^
      chapterName.hashCode ^
      bookText.hashCode ^
      content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookmarkDto &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          bookId == other.bookId &&
          bookName == other.bookName &&
          bookAuthor == other.bookAuthor &&
          chapterIndex == other.chapterIndex &&
          chapterPos == other.chapterPos &&
          chapterName == other.chapterName &&
          bookText == other.bookText &&
          content == other.content;
}

/// 目录章节条目
class ChapterItem {
  final String title;
  final String url;
  final bool isVolume;
  final bool isVip;
  final bool isPay;
  final String tag;
  final String baseUrl;

  const ChapterItem({
    required this.title,
    required this.url,
    required this.isVolume,
    required this.isVip,
    required this.isPay,
    required this.tag,
    required this.baseUrl,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      url.hashCode ^
      isVolume.hashCode ^
      isVip.hashCode ^
      isPay.hashCode ^
      tag.hashCode ^
      baseUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterItem &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          url == other.url &&
          isVolume == other.isVolume &&
          isVip == other.isVip &&
          isPay == other.isPay &&
          tag == other.tag &&
          baseUrl == other.baseUrl;
}

/// 单日阅读统计
class DailyReadingStat {
  final String date;
  final int chars;
  final int durationSeconds;

  const DailyReadingStat({
    required this.date,
    required this.chars,
    required this.durationSeconds,
  });

  @override
  int get hashCode => date.hashCode ^ chars.hashCode ^ durationSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyReadingStat &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          chars == other.chars &&
          durationSeconds == other.durationSeconds;
}

/// 调试结果条目（搜索书 / 目录章）
class DebugItem {
  final String name;
  final String author;
  final String coverUrl;
  final String bookUrl;
  final String kind;
  final String note;

  const DebugItem({
    required this.name,
    required this.author,
    required this.coverUrl,
    required this.bookUrl,
    required this.kind,
    required this.note,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      bookUrl.hashCode ^
      kind.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DebugItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          bookUrl == other.bookUrl &&
          kind == other.kind &&
          note == other.note;
}

/// 书源调试结果
class DebugResult {
  final String requestUrl;
  final String requestMethod;
  final String responseStatus;
  final String responseCharset;
  final int responseSize;
  final String responseBodyPreview;
  final List<RuleDebugStep> ruleSteps;
  final List<DebugItem> results;

  const DebugResult({
    required this.requestUrl,
    required this.requestMethod,
    required this.responseStatus,
    required this.responseCharset,
    required this.responseSize,
    required this.responseBodyPreview,
    required this.ruleSteps,
    required this.results,
  });

  @override
  int get hashCode =>
      requestUrl.hashCode ^
      requestMethod.hashCode ^
      responseStatus.hashCode ^
      responseCharset.hashCode ^
      responseSize.hashCode ^
      responseBodyPreview.hashCode ^
      ruleSteps.hashCode ^
      results.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DebugResult &&
          runtimeType == other.runtimeType &&
          requestUrl == other.requestUrl &&
          requestMethod == other.requestMethod &&
          responseStatus == other.responseStatus &&
          responseCharset == other.responseCharset &&
          responseSize == other.responseSize &&
          responseBodyPreview == other.responseBodyPreview &&
          ruleSteps == other.ruleSteps &&
          results == other.results;
}

/// EPUB 解析结果
class LocalBookInfo {
  final String title;
  final String author;
  final List<LocalChapterItem> chapters;

  const LocalBookInfo({
    required this.title,
    required this.author,
    required this.chapters,
  });

  @override
  int get hashCode => title.hashCode ^ author.hashCode ^ chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalBookInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          chapters == other.chapters;
}

/// 本地书籍章节（含正文）
class LocalChapterItem {
  final String title;
  final String content;

  const LocalChapterItem({required this.title, required this.content});

  @override
  int get hashCode => title.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalChapterItem &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          content == other.content;
}

/// 想法笔记
class NoteDto {
  final String id;
  final String bookId;
  final String chapterTitle;
  final String selectedText;
  final String noteContent;
  final int position;

  /// 章内字符偏移（对齐 Jingshiro Bookmark.chapterPos）；-1=未知
  final int chapterPos;
  final String createdAt;

  const NoteDto({
    required this.id,
    required this.bookId,
    required this.chapterTitle,
    required this.selectedText,
    required this.noteContent,
    required this.position,
    required this.chapterPos,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      chapterTitle.hashCode ^
      selectedText.hashCode ^
      noteContent.hashCode ^
      position.hashCode ^
      chapterPos.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          chapterTitle == other.chapterTitle &&
          selectedText == other.selectedText &&
          noteContent == other.noteContent &&
          position == other.position &&
          chapterPos == other.chapterPos &&
          createdAt == other.createdAt;
}

/// 阅读统计汇总
class ReadingStats {
  final int totalChars;
  final int totalDurationSeconds;
  final int todayChars;
  final int todayDurationSeconds;
  final int weekChars;
  final List<DailyReadingStat> daily;

  const ReadingStats({
    required this.totalChars,
    required this.totalDurationSeconds,
    required this.todayChars,
    required this.todayDurationSeconds,
    required this.weekChars,
    required this.daily,
  });

  @override
  int get hashCode =>
      totalChars.hashCode ^
      totalDurationSeconds.hashCode ^
      todayChars.hashCode ^
      todayDurationSeconds.hashCode ^
      weekChars.hashCode ^
      daily.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingStats &&
          runtimeType == other.runtimeType &&
          totalChars == other.totalChars &&
          totalDurationSeconds == other.totalDurationSeconds &&
          todayChars == other.todayChars &&
          todayDurationSeconds == other.todayDurationSeconds &&
          weekChars == other.weekChars &&
          daily == other.daily;
}

/// RSS 文章 DTO
class RssArticleDto {
  final String title;
  final String link;
  final String pubDate;
  final String description;
  final String content;
  final String image;
  final String origin;
  final String sort;

  const RssArticleDto({
    required this.title,
    required this.link,
    required this.pubDate,
    required this.description,
    required this.content,
    required this.image,
    required this.origin,
    required this.sort,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      link.hashCode ^
      pubDate.hashCode ^
      description.hashCode ^
      content.hashCode ^
      image.hashCode ^
      origin.hashCode ^
      sort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RssArticleDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          link == other.link &&
          pubDate == other.pubDate &&
          description == other.description &&
          content == other.content &&
          image == other.image &&
          origin == other.origin &&
          sort == other.sort;
}

/// RSS 列表结果
class RssArticlesResult {
  final List<RssArticleDto> articles;
  final String? nextUrl;

  const RssArticlesResult({required this.articles, this.nextUrl});

  @override
  int get hashCode => articles.hashCode ^ nextUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RssArticlesResult &&
          runtimeType == other.runtimeType &&
          articles == other.articles &&
          nextUrl == other.nextUrl;
}

/// 规则调试步骤
class RuleDebugStep {
  final String step;
  final String rule;
  final String result;
  final bool ok;

  const RuleDebugStep({
    required this.step,
    required this.rule,
    required this.result,
    required this.ok,
  });

  @override
  int get hashCode =>
      step.hashCode ^ rule.hashCode ^ result.hashCode ^ ok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleDebugStep &&
          runtimeType == other.runtimeType &&
          step == other.step &&
          rule == other.rule &&
          result == other.result &&
          ok == other.ok;
}

/// 搜索结果条目
class SearchItem {
  final String name;
  final String author;
  final String coverUrl;
  final String bookUrl;
  final String kind;
  final String note;

  const SearchItem({
    required this.name,
    required this.author,
    required this.coverUrl,
    required this.bookUrl,
    required this.kind,
    required this.note,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      bookUrl.hashCode ^
      kind.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          bookUrl == other.bookUrl &&
          kind == other.kind &&
          note == other.note;
}

/// 书源校验结果
class SourceValidation {
  final bool searchOk;
  final bool discoveryOk;
  final bool tocOk;
  final bool contentOk;
  final BigInt searchTimeMs;
  final List<String> errors;

  const SourceValidation({
    required this.searchOk,
    required this.discoveryOk,
    required this.tocOk,
    required this.contentOk,
    required this.searchTimeMs,
    required this.errors,
  });

  @override
  int get hashCode =>
      searchOk.hashCode ^
      discoveryOk.hashCode ^
      tocOk.hashCode ^
      contentOk.hashCode ^
      searchTimeMs.hashCode ^
      errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceValidation &&
          runtimeType == other.runtimeType &&
          searchOk == other.searchOk &&
          discoveryOk == other.discoveryOk &&
          tocOk == other.tocOk &&
          contentOk == other.contentOk &&
          searchTimeMs == other.searchTimeMs &&
          errors == other.errors;
}

/// Web API 运行状态
class WebApiStatus {
  final bool running;
  final int port;
  final String token;
  final String baseUrl;

  const WebApiStatus({
    required this.running,
    required this.port,
    required this.token,
    required this.baseUrl,
  });

  @override
  int get hashCode =>
      running.hashCode ^ port.hashCode ^ token.hashCode ^ baseUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebApiStatus &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          port == other.port &&
          token == other.token &&
          baseUrl == other.baseUrl;
}
