// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 初始化 Rust 书源引擎
void initEngine() => LegadoEngine.instance.api.crateApiInitEngine();

/// 引擎版本号
String engineVersion() => LegadoEngine.instance.api.crateApiEngineVersion();

/// 搜索书籍
List<SearchItem> search({
  required String sourceJson,
  required String keyword,
}) => LegadoEngine.instance.api.crateApiSearch(
  sourceJson: sourceJson,
  keyword: keyword,
);

/// 获取目录
List<ChapterItem> getToc({
  required String sourceJson,
  required String bookUrl,
}) => LegadoEngine.instance.api.crateApiGetToc(
  sourceJson: sourceJson,
  bookUrl: bookUrl,
);

/// 获取章节正文
String getContent({required String sourceJson, required String chapterUrl}) =>
    LegadoEngine.instance.api.crateApiGetContent(
      sourceJson: sourceJson,
      chapterUrl: chapterUrl,
    );

/// HTTP 请求并返回解码后的文本（调试用）
String httpFetch({
  required String url,
  required String method,
  String? body,
  required String charset,
  String? referer,
  String? sourceUrl,
  String? concurrentRate,
}) => LegadoEngine.instance.api.crateApiHttpFetch(
  url: url,
  method: method,
  body: body,
  charset: charset,
  referer: referer,
  sourceUrl: sourceUrl,
  concurrentRate: concurrentRate,
);

/// 目录章节条目
class ChapterItem {
  final String title;
  final String url;

  const ChapterItem({required this.title, required this.url});

  @override
  int get hashCode => title.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterItem &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          url == other.url;
}

/// 搜索结果条目
class SearchItem {
  final String name;
  final String author;
  final String coverUrl;
  final String bookUrl;
  final String kind;
  final String note;

  const SearchItem({
    required this.name,
    required this.author,
    required this.coverUrl,
    required this.bookUrl,
    required this.kind,
    required this.note,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      bookUrl.hashCode ^
      kind.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          bookUrl == other.bookUrl &&
          kind == other.kind &&
          note == other.note;
}
