// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/backup.dart';
import 'api/book_info.dart';
import 'api/cover.dart';
import 'api/db.dart';
import 'api/dict.dart';
import 'api/error.dart';
import 'api/local_book.dart';
import 'api/network.dart';
import 'api/read_record.dart';
import 'api/webdav.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class LegadoEngineApiImplPlatform
    extends BaseApiImpl<LegadoEngineWire> {
  LegadoEngineApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FutureOr<SourceBrowserResponseDto> Function(SourceBrowserRequestDto)
  dco_decode_DartFn_Inputs_source_browser_request_dto_Output_source_browser_response_dto_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppError dco_decode_app_error(dynamic raw);

  @protected
  ApplicationBinaryHttpResponseDto
  dco_decode_application_binary_http_response_dto(dynamic raw);

  @protected
  ApplicationHttpResponseDto dco_decode_application_http_response_dto(
    dynamic raw,
  );

  @protected
  BookInfoItem dco_decode_book_info_item(dynamic raw);

  @protected
  BookReadingStats dco_decode_book_reading_stats(dynamic raw);

  @protected
  BookmarkDto dco_decode_bookmark_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ContentProcessingSourceRulesDto
  dco_decode_box_autoadd_content_processing_source_rules_dto(dynamic raw);

  @protected
  SourceBrowserRequestDto dco_decode_box_autoadd_source_browser_request_dto(
    dynamic raw,
  );

  @protected
  ChapterItem dco_decode_chapter_item(dynamic raw);

  @protected
  ContentProcessingSourceRulesDto
  dco_decode_content_processing_source_rules_dto(dynamic raw);

  @protected
  ContentReplaceRuleDto dco_decode_content_replace_rule_dto(dynamic raw);

  @protected
  DailyReadingStat dco_decode_daily_reading_stat(dynamic raw);

  @protected
  DebugItem dco_decode_debug_item(dynamic raw);

  @protected
  DebugResult dco_decode_debug_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BookmarkDto> dco_decode_list_bookmark_dto(dynamic raw);

  @protected
  List<ChapterItem> dco_decode_list_chapter_item(dynamic raw);

  @protected
  List<ContentReplaceRuleDto> dco_decode_list_content_replace_rule_dto(
    dynamic raw,
  );

  @protected
  List<DailyReadingStat> dco_decode_list_daily_reading_stat(dynamic raw);

  @protected
  List<DebugItem> dco_decode_list_debug_item(dynamic raw);

  @protected
  List<LocalChapterItem> dco_decode_list_local_chapter_item(dynamic raw);

  @protected
  List<NoteDto> dco_decode_list_note_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<RemoteArchiveBookFile> dco_decode_list_remote_archive_book_file(
    dynamic raw,
  );

  @protected
  List<RssArticleDto> dco_decode_list_rss_article_dto(dynamic raw);

  @protected
  List<RuleDebugStep> dco_decode_list_rule_debug_step(dynamic raw);

  @protected
  List<SearchItem> dco_decode_list_search_item(dynamic raw);

  @protected
  List<WebDavEntry> dco_decode_list_web_dav_entry(dynamic raw);

  @protected
  LocalBookInfo dco_decode_local_book_info(dynamic raw);

  @protected
  LocalChapterItem dco_decode_local_chapter_item(dynamic raw);

  @protected
  NetworkConfigDto dco_decode_network_config_dto(dynamic raw);

  @protected
  NoteDto dco_decode_note_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ContentProcessingSourceRulesDto?
  dco_decode_opt_box_autoadd_content_processing_source_rules_dto(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ReadingStats dco_decode_reading_stats(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RemoteArchiveBookFile dco_decode_remote_archive_book_file(dynamic raw);

  @protected
  RssArticleDto dco_decode_rss_article_dto(dynamic raw);

  @protected
  RssArticlesResult dco_decode_rss_articles_result(dynamic raw);

  @protected
  RuleDebugStep dco_decode_rule_debug_step(dynamic raw);

  @protected
  SearchItem dco_decode_search_item(dynamic raw);

  @protected
  SourceBrowserRequestDto dco_decode_source_browser_request_dto(dynamic raw);

  @protected
  SourceBrowserResponseDto dco_decode_source_browser_response_dto(dynamic raw);

  @protected
  SourceValidation dco_decode_source_validation(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WebDavEntry dco_decode_web_dav_entry(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer);

  @protected
  ApplicationBinaryHttpResponseDto
  sse_decode_application_binary_http_response_dto(SseDeserializer deserializer);

  @protected
  ApplicationHttpResponseDto sse_decode_application_http_response_dto(
    SseDeserializer deserializer,
  );

  @protected
  BookInfoItem sse_decode_book_info_item(SseDeserializer deserializer);

  @protected
  BookReadingStats sse_decode_book_reading_stats(SseDeserializer deserializer);

  @protected
  BookmarkDto sse_decode_bookmark_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ContentProcessingSourceRulesDto
  sse_decode_box_autoadd_content_processing_source_rules_dto(
    SseDeserializer deserializer,
  );

  @protected
  SourceBrowserRequestDto sse_decode_box_autoadd_source_browser_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  ChapterItem sse_decode_chapter_item(SseDeserializer deserializer);

  @protected
  ContentProcessingSourceRulesDto
  sse_decode_content_processing_source_rules_dto(SseDeserializer deserializer);

  @protected
  ContentReplaceRuleDto sse_decode_content_replace_rule_dto(
    SseDeserializer deserializer,
  );

  @protected
  DailyReadingStat sse_decode_daily_reading_stat(SseDeserializer deserializer);

  @protected
  DebugItem sse_decode_debug_item(SseDeserializer deserializer);

  @protected
  DebugResult sse_decode_debug_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BookmarkDto> sse_decode_list_bookmark_dto(SseDeserializer deserializer);

  @protected
  List<ChapterItem> sse_decode_list_chapter_item(SseDeserializer deserializer);

  @protected
  List<ContentReplaceRuleDto> sse_decode_list_content_replace_rule_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DailyReadingStat> sse_decode_list_daily_reading_stat(
    SseDeserializer deserializer,
  );

  @protected
  List<DebugItem> sse_decode_list_debug_item(SseDeserializer deserializer);

  @protected
  List<LocalChapterItem> sse_decode_list_local_chapter_item(
    SseDeserializer deserializer,
  );

  @protected
  List<NoteDto> sse_decode_list_note_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<RemoteArchiveBookFile> sse_decode_list_remote_archive_book_file(
    SseDeserializer deserializer,
  );

  @protected
  List<RssArticleDto> sse_decode_list_rss_article_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<RuleDebugStep> sse_decode_list_rule_debug_step(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchItem> sse_decode_list_search_item(SseDeserializer deserializer);

  @protected
  List<WebDavEntry> sse_decode_list_web_dav_entry(SseDeserializer deserializer);

  @protected
  LocalBookInfo sse_decode_local_book_info(SseDeserializer deserializer);

  @protected
  LocalChapterItem sse_decode_local_chapter_item(SseDeserializer deserializer);

  @protected
  NetworkConfigDto sse_decode_network_config_dto(SseDeserializer deserializer);

  @protected
  NoteDto sse_decode_note_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ContentProcessingSourceRulesDto?
  sse_decode_opt_box_autoadd_content_processing_source_rules_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ReadingStats sse_decode_reading_stats(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RemoteArchiveBookFile sse_decode_remote_archive_book_file(
    SseDeserializer deserializer,
  );

  @protected
  RssArticleDto sse_decode_rss_article_dto(SseDeserializer deserializer);

  @protected
  RssArticlesResult sse_decode_rss_articles_result(
    SseDeserializer deserializer,
  );

  @protected
  RuleDebugStep sse_decode_rule_debug_step(SseDeserializer deserializer);

  @protected
  SearchItem sse_decode_search_item(SseDeserializer deserializer);

  @protected
  SourceBrowserRequestDto sse_decode_source_browser_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SourceBrowserResponseDto sse_decode_source_browser_response_dto(
    SseDeserializer deserializer,
  );

  @protected
  SourceValidation sse_decode_source_validation(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WebDavEntry sse_decode_web_dav_entry(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_source_browser_request_dto_Output_source_browser_response_dto_AnyhowException(
    FutureOr<SourceBrowserResponseDto> Function(SourceBrowserRequestDto) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer);

  @protected
  void sse_encode_application_binary_http_response_dto(
    ApplicationBinaryHttpResponseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_application_http_response_dto(
    ApplicationHttpResponseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_book_info_item(BookInfoItem self, SseSerializer serializer);

  @protected
  void sse_encode_book_reading_stats(
    BookReadingStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bookmark_dto(BookmarkDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_content_processing_source_rules_dto(
    ContentProcessingSourceRulesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_source_browser_request_dto(
    SourceBrowserRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chapter_item(ChapterItem self, SseSerializer serializer);

  @protected
  void sse_encode_content_processing_source_rules_dto(
    ContentProcessingSourceRulesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content_replace_rule_dto(
    ContentReplaceRuleDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_daily_reading_stat(
    DailyReadingStat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_debug_item(DebugItem self, SseSerializer serializer);

  @protected
  void sse_encode_debug_result(DebugResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bookmark_dto(
    List<BookmarkDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chapter_item(
    List<ChapterItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_content_replace_rule_dto(
    List<ContentReplaceRuleDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_daily_reading_stat(
    List<DailyReadingStat> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_debug_item(
    List<DebugItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_chapter_item(
    List<LocalChapterItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_dto(List<NoteDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_remote_archive_book_file(
    List<RemoteArchiveBookFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rss_article_dto(
    List<RssArticleDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rule_debug_step(
    List<RuleDebugStep> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_item(
    List<SearchItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_web_dav_entry(
    List<WebDavEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_book_info(LocalBookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_local_chapter_item(
    LocalChapterItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network_config_dto(
    NetworkConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_dto(NoteDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content_processing_source_rules_dto(
    ContentProcessingSourceRulesDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reading_stats(ReadingStats self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remote_archive_book_file(
    RemoteArchiveBookFile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rss_article_dto(RssArticleDto self, SseSerializer serializer);

  @protected
  void sse_encode_rss_articles_result(
    RssArticlesResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rule_debug_step(RuleDebugStep self, SseSerializer serializer);

  @protected
  void sse_encode_search_item(SearchItem self, SseSerializer serializer);

  @protected
  void sse_encode_source_browser_request_dto(
    SourceBrowserRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_browser_response_dto(
    SourceBrowserResponseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_validation(
    SourceValidation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_web_dav_entry(WebDavEntry self, SseSerializer serializer);
}

// Section: wire_class

class LegadoEngineWire implements BaseWire {
  factory LegadoEngineWire.fromExternalLibrary(ExternalLibrary lib) =>
      LegadoEngineWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LegadoEngineWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
