use base64::Engine;
use rquickjs::{
    Array, CatchResultExt, CaughtError, Context, Ctx, Exception, Function, Runtime, Value,
};
use std::cell::RefCell;
use std::time::{Duration, Instant};

const STDLIB: &str = include_str!("js_assets/stdlib.js");
const JSOUP: &str = include_str!("js_assets/jsoup.js");
const JS_EXECUTION_TIMEOUT: Duration = Duration::from_secs(5);
const JS_HOST_HTTP_TIMEOUT: Duration = Duration::from_secs(5);
const MAX_JS_INPUT_BYTES: usize = 256 * 1024;

thread_local! {
    /// 当前 JS 执行的 `baseUrl`，供 `java.ajax` 作 Referer
    static AJAX_REFERER: RefCell<String> = const { RefCell::new(String::new()) };
    /// 书源 JSON（含 header），供 ajax 合并请求头 — 对齐 AnalyzeUrl(source=…)
    static AJAX_SOURCE_JSON: RefCell<String> = const { RefCell::new(String::new()) };
    /// 登录头 JSON / Cookie 串
    static AJAX_LOGIN_HEADER: RefCell<String> = const { RefCell::new(String::new()) };
    /// loginCheckJs 可变 AnalyzeUrl 上下文
    static LOGIN_CHECK_CTX: RefCell<Option<LoginCheckCtx>> = const { RefCell::new(None) };
}

/// loginCheckJs 期间的 AnalyzeUrl 实例状态（对齐 Jingshiro `bindings["java"]=this`）
struct LoginCheckCtx {
    url: String,
    method: String,
    req_body: Option<String>,
    charset: String,
    source_json: String,
    source_key: String,
    header_map: std::collections::HashMap<String, String>,
    login_header: String,
    /// 本轮脚本是否调用了 putLoginHeader
    login_header_dirty: bool,
}

/// loginCheckJs 执行结果
#[derive(Debug, Clone)]
pub struct LoginCheckResult {
    pub body: String,
    pub url: String,
    pub login_header: Option<String>,
}

/// 将 QuickJS CaughtError 展开为可读信息（避免仅见 "Exception generated by QuickJS"）
fn format_caught_err(prefix: &str, err: CaughtError<'_>) -> String {
    match err {
        CaughtError::Exception(ex) => {
            let msg = ex.message().unwrap_or_default();
            let stack = ex.stack().unwrap_or_default();
            if msg.eq_ignore_ascii_case("interrupted") {
                return format!(
                    "{prefix}: JS 执行超时（超过 {} 秒）",
                    JS_EXECUTION_TIMEOUT.as_secs()
                );
            }
            if !msg.is_empty() && !stack.is_empty() {
                format!("{prefix}: {msg}\n{stack}")
            } else if !msg.is_empty() {
                format!("{prefix}: {msg}")
            } else {
                format!("{prefix}: {ex}")
            }
        }
        CaughtError::Value(v) => format!("{prefix}: {v:?}"),
        CaughtError::Error(e) => format!("{prefix}: {e}"),
    }
}

fn with_js_context<T>(
    script: &str,
    js_lib: &str,
    operation: impl for<'js> FnOnce(Ctx<'js>) -> Result<T, String>,
) -> Result<T, String> {
    for (label, value) in [("脚本", script), ("jsLib", js_lib)] {
        if value.len() > MAX_JS_INPUT_BYTES {
            return Err(format!(
                "JS 执行失败: {label}输入超过 {} 字节上限（实际 {} 字节）",
                MAX_JS_INPUT_BYTES,
                value.len()
            ));
        }
    }

    let rt = Runtime::new().map_err(|e| format!("JS Runtime 失败: {e}"))?;
    let deadline = Instant::now() + JS_EXECUTION_TIMEOUT;
    rt.set_interrupt_handler(Some(Box::new(move || Instant::now() >= deadline)));
    let ctx = Context::full(&rt).map_err(|e| format!("JS Context 失败: {e}"))?;
    ctx.with(operation)
}

fn register_host_apis(ctx: &Ctx<'_>) -> Result<(), String> {
    let base64_encode = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, value: String| {
            Ok::<String, rquickjs::Error>(
                base64::engine::general_purpose::STANDARD.encode(value.as_bytes()),
            )
        }
    })
    .map_err(|e| format!("注册 Base64 encode 失败: {e}"))?;
    ctx.globals()
        .set("__legado_base64_encode", base64_encode)
        .map_err(|e| format!("注入 Base64 encode 失败: {e}"))?;

    let hex_decode = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, value: String| {
            Ok::<String, rquickjs::Error>(decode_hex_or_original(&value))
        }
    })
    .map_err(|e| format!("注册 hex decode 失败: {e}"))?;
    ctx.globals()
        .set("__legado_hex_decode", hex_decode)
        .map_err(|e| format!("注入 hex decode 失败: {e}"))?;

    let jsonpath_read = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, json: String, path: String| {
            let result = serde_json::from_str::<serde_json::Value>(&json)
                .ok()
                .and_then(|value| super::json_util::resolve_path(&value, &path).ok())
                .unwrap_or(serde_json::Value::Null);
            Ok::<String, rquickjs::Error>(
                serde_json::to_string(&result).unwrap_or_else(|_| "null".to_string()),
            )
        }
    })
    .map_err(|e| format!("注册 JSONPath read 失败: {e}"))?;
    ctx.globals()
        .set("__legado_jsonpath_read", jsonpath_read)
        .map_err(|e| format!("注入 JSONPath read 失败: {e}"))?;

    let encrypt = Function::new(ctx.clone(), {
        move |ctx: Ctx<'_>, transformation: String, key: String, iv: String, data: String| {
            match super::js_crypto::encrypt_base64(&transformation, &key, &iv, &data) {
                Ok(s) => Ok(s),
                Err(e) => Err(Exception::throw_message(
                    &ctx,
                    &format!("AES encrypt 失败: {e}"),
                )),
            }
        }
    })
    .map_err(|e| format!("注册 AES encrypt 失败: {e}"))?;
    ctx.globals()
        .set("__legado_aes_encrypt_b64", encrypt)
        .map_err(|e| format!("注入 AES encrypt 失败: {e}"))?;

    let decrypt = Function::new(ctx.clone(), {
        move |ctx: Ctx<'_>, transformation: String, key: String, iv: String, data: String| {
            match super::js_crypto::decrypt_str(&transformation, &key, &iv, &data) {
                Ok(s) => Ok(s),
                Err(e) => Err(Exception::throw_message(
                    &ctx,
                    &format!("AES decrypt 失败: {e}"),
                )),
            }
        }
    })
    .map_err(|e| format!("注册 AES decrypt 失败: {e}"))?;
    ctx.globals()
        .set("__legado_aes_decrypt_str", decrypt)
        .map_err(|e| format!("注入 AES decrypt 失败: {e}"))?;

    // Jingshiro JsExtensions.ajax — 同步拉页面（失败返回空串，调用方常 try/catch）
    let ajax = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, url: String| -> Result<String, rquickjs::Error> {
            let referer = AJAX_REFERER.with(|r| r.borrow().clone());
            let source_json = AJAX_SOURCE_JSON.with(|r| r.borrow().clone());
            let login_header = AJAX_LOGIN_HEADER.with(|r| r.borrow().clone());
            match crate::http::client::ajax_blocking_with_deadline(
                &url,
                if referer.is_empty() {
                    None
                } else {
                    Some(referer.as_str())
                },
                if source_json.is_empty() {
                    None
                } else {
                    Some(source_json.as_str())
                },
                if login_header.is_empty() {
                    None
                } else {
                    Some(login_header.as_str())
                },
                JS_HOST_HTTP_TIMEOUT,
            ) {
                Ok(body) => Ok(body),
                Err(_) => Ok(String::new()),
            }
        }
    })
    .map_err(|e| format!("注册 java.ajax 失败: {e}"))?;
    ctx.globals()
        .set("__legado_java_ajax", ajax)
        .map_err(|e| format!("注入 java.ajax 失败: {e}"))?;

    // Jingshiro `java.ajaxAll`：并发执行 URL，并保持 StrResponse 的方法形状。
    let ajax_all = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, payload: String| -> Result<String, rquickjs::Error> {
            let urls = serde_json::from_str::<Vec<String>>(&payload).unwrap_or_default();
            let referer = AJAX_REFERER.with(|r| r.borrow().clone());
            let source_json = AJAX_SOURCE_JSON.with(|r| r.borrow().clone());
            let login_header = AJAX_LOGIN_HEADER.with(|r| r.borrow().clone());
            let handles = urls.into_iter().map(|url| {
                let referer = referer.clone();
                let source_json = source_json.clone();
                let login_header = login_header.clone();
                std::thread::spawn(move || {
                    let started = Instant::now();
                    let result = crate::http::client::ajax_blocking_with_deadline(
                        &url,
                        if referer.is_empty() {
                            None
                        } else {
                            Some(referer.as_str())
                        },
                        if source_json.is_empty() {
                            None
                        } else {
                            Some(source_json.as_str())
                        },
                        if login_header.is_empty() {
                            None
                        } else {
                            Some(login_header.as_str())
                        },
                        JS_HOST_HTTP_TIMEOUT,
                    );
                    match result {
                        Ok(body) => {
                            let raw = body.clone();
                            serde_json::json!({
                            "body": body,
                            "url": url,
                            "code": 200,
                            "message": "",
                            "headers": {},
                            "raw": raw,
                            "callTime": started.elapsed().as_millis(),
                            })
                        }
                        Err(error) => serde_json::json!({
                            "body": "",
                            "url": url,
                            "code": 0,
                            "message": error,
                            "headers": {},
                            "raw": "",
                            "callTime": started.elapsed().as_millis(),
                        }),
                    }
                })
            });
            let rows = handles
                .map(|handle| {
                    handle.join().unwrap_or_else(|_| {
                        serde_json::json!({
                            "body": "",
                            "url": "",
                            "code": 0,
                            "message": "java.ajaxAll 线程异常",
                            "headers": {},
                            "raw": "",
                            "callTime": 0,
                        })
                    })
                })
                .collect::<Vec<_>>();
            Ok(serde_json::to_string(&rows).unwrap_or_else(|_| "[]".to_string()))
        }
    })
    .map_err(|e| format!("注册 java.ajaxAll 失败: {e}"))?;
    ctx.globals()
        .set("__legado_java_ajax_all", ajax_all)
        .map_err(|e| format!("注入 java.ajaxAll 失败: {e}"))?;

    // 登录/源脚本注入 ajax 上下文（书源 header + 登录头）
    let set_ajax_ctx = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, source_json: String, login_header: String| {
            AJAX_SOURCE_JSON.with(|r| *r.borrow_mut() = source_json);
            AJAX_LOGIN_HEADER.with(|r| *r.borrow_mut() = login_header);
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 set_ajax_ctx 失败: {e}"))?;
    ctx.globals()
        .set("__legado_set_ajax_ctx", set_ajax_ctx)
        .map_err(|e| format!("注入 set_ajax_ctx 失败: {e}"))?;

    // —— loginCheckJs AnalyzeUrl 绑定（对照 reference/.../AnalyzeUrl.kt + jsHelp.md）——
    // java.getHeaderMap / initUrl / getStrResponse
    // source.getLoginHeader / putLoginHeader / getHeaderMap(true)
    register_login_check_host_apis(ctx)?;

    let cache_put = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, key: String, value: String, seconds: i64| {
            super::js_cache::put(&key, &value, seconds);
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 cache.put 失败: {e}"))?;
    ctx.globals()
        .set("__legado_cache_put", cache_put)
        .map_err(|e| format!("注入 cache.put 失败: {e}"))?;

    let cache_get = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, key: String| Ok::<String, rquickjs::Error>(super::js_cache::get(&key))
    })
    .map_err(|e| format!("注册 cache.get 失败: {e}"))?;
    ctx.globals()
        .set("__legado_cache_get", cache_get)
        .map_err(|e| format!("注入 cache.get 失败: {e}"))?;

    let cache_delete = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, key: String| {
            super::js_cache::delete(&key);
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 cache.delete 失败: {e}"))?;
    ctx.globals()
        .set("__legado_cache_delete", cache_delete)
        .map_err(|e| format!("注入 cache.delete 失败: {e}"))?;

    Ok(())
}

fn decode_hex_or_original(value: &str) -> String {
    let compact: String = value.chars().filter(|ch| !ch.is_whitespace()).collect();
    if compact.is_empty()
        || compact.len() % 2 != 0
        || !compact.chars().all(|ch| ch.is_ascii_hexdigit())
    {
        return value.to_string();
    }
    let bytes = compact
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let text = std::str::from_utf8(pair).ok()?;
            u8::from_str_radix(text, 16).ok()
        })
        .collect::<Option<Vec<_>>>();
    bytes
        .and_then(|bytes| String::from_utf8(bytes).ok())
        .unwrap_or_else(|| value.to_string())
}

fn init_context(ctx: &Ctx<'_>, js_lib: &str, base_url: &str) -> Result<(), String> {
    AJAX_REFERER.with(|r| {
        *r.borrow_mut() = base_url.to_string();
    });
    AJAX_SOURCE_JSON.with(|r| r.borrow_mut().clear());
    AJAX_LOGIN_HEADER.with(|r| r.borrow_mut().clear());
    register_host_apis(ctx)?;
    ctx.eval::<(), _>(STDLIB.as_bytes())
        .catch(ctx)
        .map_err(|e| format_caught_err("JS 标准库加载失败", e))?;
    ctx.eval::<(), _>(JSOUP.as_bytes())
        .catch(ctx)
        .map_err(|e| format_caught_err("Jsoup 兼容层加载失败", e))?;
    let base_code = format!("baseUrl = {};", json_escape(base_url));
    ctx.eval::<(), _>(base_code.as_bytes())
        .catch(ctx)
        .map_err(|e| format_caught_err("baseUrl 注入失败", e))?;
    if !js_lib.trim().is_empty() {
        ctx.eval::<(), _>(js_lib.as_bytes())
            .catch(ctx)
            .map_err(|e| format_caught_err("jsLib 加载失败", e))?;
    }
    Ok(())
}

fn value_to_string<'js>(ctx: &Ctx<'js>, v: Value<'js>) -> Result<String, String> {
    if v.is_null() || v.is_undefined() {
        return Ok(String::new());
    }
    if v.is_string() {
        if let Some(s) = v.as_string() {
            return s.to_string().map_err(|e| format!("JS 字符串转换失败: {e}"));
        }
        return Ok(String::new());
    }
    if v.is_number() {
        return Ok(v.as_number().map(|n| n.to_string()).unwrap_or_default());
    }
    if v.is_bool() {
        return Ok(v.as_bool().map(|b| b.to_string()).unwrap_or_default());
    }
    match ctx
        .json_stringify(v)
        .map_err(|e| format!("JS JSON 序列化失败: {e}"))?
    {
        Some(s) => s
            .to_string()
            .map_err(|e| format!("JS JSON 字符串转换失败: {e}")),
        None => Ok(String::new()),
    }
}

/// 新一轮书源操作前清空跨 Runtime 的书源 `cache`
pub fn reset_cache() -> Result<(), String> {
    super::js_cache::clear();
    Ok(())
}

/// 执行裸 JS 脚本（搜索 @js: / URL 模板用）
pub fn run_eval_script(script: &str, js_lib: &str, base_url: &str) -> Result<String, String> {
    let script = normalize_rhino_with(script);
    with_js_context(script.as_ref(), js_lib, |ctx| {
        init_context(&ctx, js_lib, base_url)?;
        let v: Value = ctx
            .eval(script.as_bytes())
            .catch(&ctx)
            .map_err(|e| format_caught_err("JS 执行失败", e))?;
        value_to_string(&ctx, v)
    })
}

/// `@js:` 搜索 URL 脚本
pub fn run_search_js(
    script: &str,
    keyword: &str,
    js_lib: &str,
    base_url: &str,
    page: i32,
) -> Result<String, String> {
    let base_host = json_escape(&crate::http::client::base_url(base_url));
    let code = format!(
        "var key = {};\nvar page = {};\nvar baseUrl = {};\nfunction Base() {{ return {}; }}\n{}\n{}",
        json_escape(keyword),
        page,
        json_escape(base_url),
        base_host,
        js_lib,
        script
    );
    run_eval_script(&code, "", base_url)
}

/// 含 `<js>` 的 URL 模板
pub fn run_url_template_js(
    template: &str,
    keyword: &str,
    js_lib: &str,
    base_url: &str,
    page: i32,
) -> Result<String, String> {
    let script = extract_js_block(template).ok_or("URL 模板无 <js> 块")?;
    let base_host = json_escape(&crate::http::client::base_url(base_url));
    let code = format!(
        "var result = {{\"articleid\":\"\"}};\nvar baseUrl = {};\nvar articleid = '';\nvar key = {};\nvar page = {};\nfunction J(obj) {{ return obj; }}\nfunction Base() {{ return {}; }}\n{}\n{}",
        json_escape(base_url),
        json_escape(keyword),
        page,
        base_host,
        js_lib,
        script
    );
    run_eval_script(&code, "", base_url)
}

/// 执行 Legado `<js>...</js>` 脚本，`result` 为输入数据
pub fn run_with_result(
    script: &str,
    result: &str,
    js_lib: &str,
    base_url: &str,
) -> Result<String, String> {
    run_with_result_opts(script, result, js_lib, base_url, None)
}

/// Execute a JS rule and convert its final value as `AnalyzeRule.getString` does.
/// Structured callers should continue using [`run_with_result`], which preserves
/// arrays/objects as JSON at the Rust parsing boundary.
pub fn run_with_result_as_string(
    script: &str,
    result: &str,
    js_lib: &str,
    base_url: &str,
) -> Result<String, String> {
    run_with_result_opts_as_string(script, result, js_lib, base_url, None)
}

/// 同 [`run_with_result`]，可注入 `book.bookUrl`（对齐 Jingshiro AnalyzeRule + Book）
pub fn run_with_result_opts(
    script: &str,
    result: &str,
    js_lib: &str,
    base_url: &str,
    book_url: Option<&str>,
) -> Result<String, String> {
    run_with_result_opts_internal(
        script, result, js_lib, base_url, book_url, None, None, false,
    )
}

pub fn run_with_result_opts_as_string(
    script: &str,
    result: &str,
    js_lib: &str,
    base_url: &str,
    book_url: Option<&str>,
) -> Result<String, String> {
    run_with_result_opts_internal(script, result, js_lib, base_url, book_url, None, None, true)
}

pub fn run_with_book_as_string(
    script: &str,
    result: &str,
    js_lib: &str,
    base_url: &str,
    book_name: &str,
    book_author: &str,
) -> Result<String, String> {
    run_with_result_opts_internal(
        script,
        result,
        js_lib,
        base_url,
        None,
        Some(book_name),
        Some(book_author),
        true,
    )
}

fn run_with_result_opts_internal(
    script: &str,
    result: &str,
    js_lib: &str,
    base_url: &str,
    book_url: Option<&str>,
    book_name: Option<&str>,
    book_author: Option<&str>,
    as_string: bool,
) -> Result<String, String> {
    let script = normalize_rhino_with(script);
    with_js_context(script.as_ref(), js_lib, |ctx| {
        init_context(&ctx, js_lib, base_url)?;
        let escaped = serde_json::to_string(result).unwrap_or_else(|_| "\"\"".to_string());
        let book_url = book_url.unwrap_or(base_url);
        let book_inject = format!(
            "var book = {{ bookUrl: {}, name: {}, author: {} }};\n",
            json_escape(book_url),
            json_escape(book_name.unwrap_or("")),
            json_escape(book_author.unwrap_or("")),
        );
        let code = format!(
            "{book_inject}legadoResult = {escaped}; var result = typeof legadoResult === 'string' ? legadoResult : JSON.stringify(legadoResult);\n{script}"
        );
        let v: Value = ctx
            .eval(code.as_bytes())
            .catch(&ctx)
            .map_err(|e| format_caught_err("JS 执行失败", e))?;
        if as_string {
            value_to_js_string(&ctx, v)
        } else {
            value_to_string(&ctx, v)
        }
    })
}

fn normalize_rhino_with(script: &str) -> std::borrow::Cow<'_, str> {
    static WITH_BLOCK: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
    static IMPLICIT_FOR_OF: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
    let with_block =
        WITH_BLOCK.get_or_init(|| regex::Regex::new(r"(?i)\bwith\s*\([^)]*\)\s*\{").unwrap());
    let implicit_for_of = IMPLICIT_FOR_OF.get_or_init(|| {
        regex::Regex::new(r"\bfor\s*\(\s*([A-Za-z_$][A-Za-z0-9_$]*)\s+of\s+").unwrap()
    });
    if !with_block.is_match(script) && !implicit_for_of.is_match(script) {
        return std::borrow::Cow::Borrowed(script);
    }
    let without_with = with_block.replace_all(script, "{");
    std::borrow::Cow::Owned(
        implicit_for_of
            .replace_all(without_with.as_ref(), "for (var $1 of ")
            .into_owned(),
    )
}

/// 纯 property 规则名（如 `chaptername` / `chapterurl`），无 CSS/`@`
pub fn is_plain_property_rule(rule: &str) -> bool {
    let r = rule.trim();
    !r.is_empty()
        && !r.contains('@')
        && !r.contains('<')
        && !r.contains('.')
        && !r.contains('#')
        && !r.contains(' ')
        && !r.contains(':')
        && r.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// 对 HTML 执行 `<js>` 脚本并返回变换后的 HTML/文本
pub fn run_html_js(
    script: &str,
    html: &str,
    js_lib: &str,
    base_url: &str,
) -> Result<String, String> {
    run_with_result(script, html, js_lib, base_url)
}

/// 从书源 JSON 读取顶层 `loginCheckJs`（空则跳过）
fn login_check_js_from_source_json(source_json: &str) -> String {
    serde_json::from_str::<serde_json::Value>(source_json)
        .ok()
        .and_then(|v| {
            v.get("loginCheckJs")
                .and_then(|x| x.as_str())
                .map(|s| s.to_string())
        })
        .unwrap_or_default()
}

fn js_lib_from_source_json(source_json: &str) -> String {
    serde_json::from_str::<serde_json::Value>(source_json)
        .ok()
        .and_then(|v| {
            v.get("jsLib")
                .and_then(|x| x.as_str())
                .map(|s| s.to_string())
        })
        .unwrap_or_default()
}

fn book_source_key(source_json: &str) -> String {
    serde_json::from_str::<serde_json::Value>(source_json)
        .ok()
        .and_then(|v| {
            v.get("bookSourceUrl")
                .or_else(|| v.get("sourceUrl"))
                .and_then(|x| x.as_str())
                .map(|s| s.to_string())
        })
        .unwrap_or_default()
}

fn header_map_from_source_json(source_json: &str) -> std::collections::HashMap<String, String> {
    let mut map = std::collections::HashMap::new();
    let Ok(v) = serde_json::from_str::<serde_json::Value>(source_json) else {
        return map;
    };
    if let Some(h) = v.get("header") {
        match h {
            serde_json::Value::Object(o) => {
                for (k, val) in o {
                    let s = match val {
                        serde_json::Value::String(s) => s.clone(),
                        other => other.to_string(),
                    };
                    if !s.is_empty() {
                        map.insert(k.clone(), s);
                    }
                }
            }
            serde_json::Value::String(s) => {
                if let Ok(obj) = serde_json::from_str::<serde_json::Value>(s) {
                    if let serde_json::Value::Object(o) = obj {
                        for (k, val) in o {
                            let s = match val {
                                serde_json::Value::String(s) => s.clone(),
                                other => other.to_string(),
                            };
                            if !s.is_empty() {
                                map.insert(k, s);
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }
    map
}

fn merge_login_into_map(map: &mut std::collections::HashMap<String, String>, login_header: &str) {
    let t = login_header.trim();
    if t.is_empty() {
        return;
    }
    if let Ok(v) = serde_json::from_str::<serde_json::Value>(t) {
        if let serde_json::Value::Object(o) = v {
            for (k, val) in o {
                let s = match val {
                    serde_json::Value::String(s) => s,
                    other => other.to_string(),
                };
                if !s.is_empty() {
                    map.insert(k, s);
                }
            }
            return;
        }
    }
    map.insert("Cookie".to_string(), t.to_string());
}

fn register_login_check_host_apis(ctx: &Ctx<'_>) -> Result<(), String> {
    let get_hm = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>| -> Result<String, rquickjs::Error> {
            LOGIN_CHECK_CTX.with(|c| {
                Ok(c.borrow()
                    .as_ref()
                    .map(|ctx| {
                        serde_json::to_string(&ctx.header_map).unwrap_or_else(|_| "{}".into())
                    })
                    .unwrap_or_else(|| "{}".into()))
            })
        }
    })
    .map_err(|e| format!("注册 lc getHeaderMap 失败: {e}"))?;
    ctx.globals()
        .set("__legado_lc_header_map_json", get_hm)
        .map_err(|e| format!("注入 lc getHeaderMap 失败: {e}"))?;

    let put_h = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, key: String, val: String| {
            LOGIN_CHECK_CTX.with(|c| {
                if let Some(ctx) = c.borrow_mut().as_mut() {
                    ctx.header_map.insert(key, val);
                }
            });
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 lc putHeader 失败: {e}"))?;
    ctx.globals()
        .set("__legado_lc_header_put", put_h)
        .map_err(|e| format!("注入 lc putHeader 失败: {e}"))?;

    let put_all = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, json: String| {
            LOGIN_CHECK_CTX.with(|c| {
                if let Some(ctx) = c.borrow_mut().as_mut() {
                    merge_login_into_map(&mut ctx.header_map, &json);
                }
            });
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 lc putAll 失败: {e}"))?;
    ctx.globals()
        .set("__legado_lc_header_put_all", put_all)
        .map_err(|e| format!("注入 lc putAll 失败: {e}"))?;

    let get_lh = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>| -> Result<String, rquickjs::Error> {
            LOGIN_CHECK_CTX.with(|c| {
                Ok(c.borrow()
                    .as_ref()
                    .map(|ctx| {
                        if !ctx.login_header.is_empty() {
                            ctx.login_header.clone()
                        } else {
                            crate::http::login_header_store::get(&ctx.source_key)
                        }
                    })
                    .unwrap_or_default())
            })
        }
    })
    .map_err(|e| format!("注册 getLoginHeader 失败: {e}"))?;
    ctx.globals()
        .set("__legado_lc_get_login_header", get_lh)
        .map_err(|e| format!("注入 getLoginHeader 失败: {e}"))?;

    let put_lh = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, header: String| {
            LOGIN_CHECK_CTX.with(|c| {
                if let Some(ctx) = c.borrow_mut().as_mut() {
                    ctx.login_header = header.clone();
                    ctx.login_header_dirty = true;
                    crate::http::login_header_store::put(&ctx.source_key, &header);
                    merge_login_into_map(&mut ctx.header_map, &header);
                    // Cookie → jar（BaseSource.putLoginHeader）
                    if let Ok(v) = serde_json::from_str::<serde_json::Value>(&header) {
                        if let Some(cookie) = v
                            .get("Cookie")
                            .or_else(|| v.get("cookie"))
                            .and_then(|x| x.as_str())
                        {
                            crate::http::client::replace_cookie_for_source(&ctx.source_key, cookie);
                        }
                    } else if header.contains('=') {
                        crate::http::client::replace_cookie_for_source(&ctx.source_key, &header);
                    }
                    AJAX_LOGIN_HEADER.with(|r| *r.borrow_mut() = header);
                }
            });
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 putLoginHeader 失败: {e}"))?;
    ctx.globals()
        .set("__legado_lc_put_login_header", put_lh)
        .map_err(|e| format!("注入 putLoginHeader 失败: {e}"))?;

    let src_hm = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, has_login: bool| -> Result<String, rquickjs::Error> {
            LOGIN_CHECK_CTX.with(|c| {
                let borrowed = c.borrow();
                let Some(ctx) = borrowed.as_ref() else {
                    return Ok("{}".into());
                };
                let mut map = header_map_from_source_json(&ctx.source_json);
                if has_login {
                    let lh = if !ctx.login_header.is_empty() {
                        ctx.login_header.clone()
                    } else {
                        crate::http::login_header_store::get(&ctx.source_key)
                    };
                    merge_login_into_map(&mut map, &lh);
                }
                Ok(serde_json::to_string(&map).unwrap_or_else(|_| "{}".into()))
            })
        }
    })
    .map_err(|e| format!("注册 source.getHeaderMap 失败: {e}"))?;
    ctx.globals()
        .set("__legado_lc_source_header_map", src_hm)
        .map_err(|e| format!("注入 source.getHeaderMap 失败: {e}"))?;

    let init_url = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>| {
            // 对齐 AnalyzeUrl.initUrl 轻量版：用最新登录头刷新 header_map（URL 已在外层解析）
            LOGIN_CHECK_CTX.with(|c| {
                if let Some(ctx) = c.borrow_mut().as_mut() {
                    merge_login_into_map(&mut ctx.header_map, &ctx.login_header);
                }
            });
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 initUrl 失败: {e}"))?;
    ctx.globals()
        .set("__legado_lc_init_url", init_url)
        .map_err(|e| format!("注入 initUrl 失败: {e}"))?;

    let get_str = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>| -> Result<String, rquickjs::Error> {
            let (url, method, body, charset, headers) = LOGIN_CHECK_CTX.with(|c| {
                let ctx = c.borrow();
                let Some(ctx) = ctx.as_ref() else {
                    return (
                        String::new(),
                        "GET".into(),
                        None,
                        "UTF-8".into(),
                        std::collections::HashMap::new(),
                    );
                };
                (
                    ctx.url.clone(),
                    ctx.method.clone(),
                    ctx.req_body.clone(),
                    ctx.charset.clone(),
                    ctx.header_map.clone(),
                )
            });
            if url.is_empty() {
                return Ok(r#"{"body":"","url":"","code":500}"#.into());
            }
            match crate::http::client::fetch_blocking_with_header_map(
                &url,
                &method,
                body.as_deref(),
                &charset,
                &headers,
            ) {
                Ok((code, body)) => Ok(serde_json::json!({
                    "body": body,
                    "url": url,
                    "code": code,
                })
                .to_string()),
                Err(e) => Ok(serde_json::json!({
                    "body": format!("Error Response\n{e}"),
                    "url": url,
                    "code": 500,
                })
                .to_string()),
            }
        }
    })
    .map_err(|e| format!("注册 getStrResponse 失败: {e}"))?;
    ctx.globals()
        .set("__legado_lc_get_str_response", get_str)
        .map_err(|e| format!("注入 getStrResponse 失败: {e}"))?;

    let start_browser = Function::new(ctx.clone(), {
        move |ctx: Ctx<'_>,
              url: String,
              title: String,
              refetch_after_success: bool,
              has_html: bool,
              html: String|
              -> Result<String, rquickjs::Error> {
            if url.encode_utf16().count() >= 64 * 1024 {
                return Err(Exception::throw_message(
                    &ctx,
                    "startBrowser parameter url too long",
                ));
            }
            let (source_key, mut headers) = LOGIN_CHECK_CTX.with(|c| {
                let borrowed = c.borrow();
                borrowed
                    .as_ref()
                    .map(|state| (state.source_key.clone(), state.header_map.clone()))
                    .unwrap_or_default()
            });
            let config = crate::http::client::parse_url_config(&url, "");
            headers.extend(config.headers.clone());
            let mut initial_html = has_html.then_some(html);
            if initial_html.is_none() && config.method.eq_ignore_ascii_case("POST") {
                initial_html = Some(
                    crate::http::client::fetch_blocking_with_header_map(
                        &config.url,
                        &config.method,
                        config.body.as_deref(),
                        &config.charset,
                        &headers,
                    )
                    .map_err(|e| Exception::throw_message(&ctx, &e))?
                    .1,
                );
            }
            let response = crate::browser_host::invoke(crate::api::SourceBrowserRequestDto {
                source_key,
                url: config.url.clone(),
                title,
                html: initial_html.clone(),
                headers: headers.clone(),
                refetch_after_success,
            })
            .map_err(|e| Exception::throw_message(&ctx, &e))?;

            let (final_url, body) = if refetch_after_success {
                if let Some(html) = initial_html {
                    (config.url, html)
                } else {
                    let (_, body, final_url) =
                        crate::http::client::fetch_blocking_response_with_header_map(
                            &config.url,
                            &config.method,
                            config.body.as_deref(),
                            &config.charset,
                            &headers,
                        )
                        .map_err(|e| Exception::throw_message(&ctx, &e))?;
                    (final_url, body)
                }
            } else {
                let final_url = if response.final_url.trim().is_empty() {
                    config.url
                } else {
                    response.final_url
                };
                (final_url, response.body)
            };
            Ok(serde_json::json!({
                "body": body,
                "url": final_url,
                "code": 200,
            })
            .to_string())
        }
    })
    .map_err(|e| format!("注册 startBrowserAwait 失败: {e}"))?;
    ctx.globals()
        .set("__legado_lc_start_browser", start_browser)
        .map_err(|e| format!("注入 startBrowserAwait 失败: {e}"))?;

    Ok(())
}

/// 对齐 Jingshiro：`AnalyzeUrl.getStrResponseAwait` 之后执行 `loginCheckJs`。
///
/// 绑定清单（reference/Jingshiro-legado）：
/// - `result` = StrResponse；`java` ≈ AnalyzeUrl（getHeaderMap / initUrl / getStrResponse）
/// - `source.putLoginHeader` / `getLoginHeader` / `getHeaderMap(true)`
pub fn apply_login_check_js(
    source_json: &str,
    body: &str,
    request_url: &str,
    method: &str,
    req_body: Option<&str>,
    charset: &str,
) -> LoginCheckResult {
    let script = login_check_js_from_source_json(source_json);
    let script = script.trim();
    let fallback = LoginCheckResult {
        body: body.to_string(),
        url: request_url.to_string(),
        login_header: None,
    };
    if script.is_empty() {
        return fallback;
    }
    let js_lib = js_lib_from_source_json(source_json);
    match run_login_check_script(
        script,
        body,
        &js_lib,
        request_url,
        source_json,
        method,
        req_body,
        charset,
    ) {
        Ok(out) => {
            if out.body.is_empty() {
                LoginCheckResult {
                    body: body.to_string(),
                    url: out.url,
                    login_header: out.login_header,
                }
            } else {
                out
            }
        }
        Err(e) => {
            eprintln!("[loginCheckJs] 执行失败（保留原响应）: {e}");
            fallback
        }
    }
}

/// 在专用阻塞线程执行同步 QuickJS。Dart 主 isolate 可在原 FRB Future 挂起期间处理 WebView 回调。
pub async fn apply_login_check_js_async(
    source_json: &str,
    body: &str,
    request_url: &str,
    method: &str,
    req_body: Option<&str>,
    charset: &str,
) -> LoginCheckResult {
    let source_json = source_json.to_string();
    let body = body.to_string();
    let request_url = request_url.to_string();
    let method = method.to_string();
    let req_body = req_body.map(str::to_string);
    let charset = charset.to_string();
    let fallback = LoginCheckResult {
        body: body.clone(),
        url: request_url.clone(),
        login_header: None,
    };
    tokio::task::spawn_blocking(move || {
        apply_login_check_js(
            &source_json,
            &body,
            &request_url,
            &method,
            req_body.as_deref(),
            &charset,
        )
    })
    .await
    .unwrap_or_else(|e| {
        eprintln!("[loginCheckJs] 阻塞线程失败（保留原响应）: {e}");
        fallback
    })
}

fn run_login_check_script(
    script: &str,
    body: &str,
    js_lib: &str,
    request_url: &str,
    source_json: &str,
    method: &str,
    req_body: Option<&str>,
    charset: &str,
) -> Result<LoginCheckResult, String> {
    let source_key = book_source_key(source_json);
    let mut header_map = header_map_from_source_json(source_json);
    let mut login_header = crate::http::login_header_store::get(&source_key);
    if login_header.is_empty() {
        // 已 merge 进 source.header 的登录头也可用
        if let Some(cookie) = header_map.get("Cookie").cloned() {
            login_header = serde_json::json!({ "Cookie": cookie }).to_string();
        }
    }
    merge_login_into_map(&mut header_map, &login_header);

    LOGIN_CHECK_CTX.with(|c| {
        *c.borrow_mut() = Some(LoginCheckCtx {
            url: request_url.to_string(),
            method: if method.is_empty() {
                "GET".into()
            } else {
                method.to_string()
            },
            req_body: req_body.map(|s| s.to_string()),
            charset: if charset.is_empty() {
                "UTF-8".into()
            } else {
                charset.to_string()
            },
            source_json: source_json.to_string(),
            source_key: source_key.clone(),
            header_map,
            login_header: login_header.clone(),
            login_header_dirty: false,
        });
    });

    let result = with_js_context(script, js_lib, |ctx| {
        init_context(&ctx, js_lib, request_url)?;
        AJAX_SOURCE_JSON.with(|r| *r.borrow_mut() = source_json.to_string());
        AJAX_LOGIN_HEADER.with(|r| *r.borrow_mut() = login_header.clone());
        let escaped_body = serde_json::to_string(body).unwrap_or_else(|_| "\"\"".to_string());
        let escaped_url = json_escape(request_url);
        let escaped_src = json_escape(source_json);
        let escaped_key = json_escape(&source_key);

        let mut code = String::new();
        code.push_str(
            r##"
function __StrResponse(body, url, code) {
  this._body = String(body == null ? '' : body);
  this._url = String(url == null ? '' : url);
  this._code = (code == null || code === undefined) ? 200 : (code|0);
}
__StrResponse.prototype.body = function() { return this._body; };
__StrResponse.prototype.url = function() { return this._url; };
__StrResponse.prototype.code = function() { return this._code; };
__StrResponse.prototype.toString = function() { return this._body; };
__StrResponse.prototype.valueOf = function() { return this._body; };
__StrResponse.prototype.replace = function() {
  return String.prototype.replace.apply(this._body, arguments);
};
__StrResponse.prototype.match = function() {
  return String.prototype.match.apply(this._body, arguments);
};
__StrResponse.prototype.indexOf = function() {
  return String.prototype.indexOf.apply(this._body, arguments);
};
__StrResponse.prototype.substring = function() {
  return String.prototype.substring.apply(this._body, arguments);
};
function __wrapHeaderMap(raw) {
  var o = raw && typeof raw === 'object' ? raw : {};
  o.put = function(k, v) {
    this[String(k)] = String(v == null ? '' : v);
    if (typeof __legado_lc_header_put === 'function') {
      __legado_lc_header_put(String(k), String(v == null ? '' : v));
    }
    return this;
  };
  o.putAll = function(other) {
    var src = other;
    if (typeof other === 'string') {
      try { src = JSON.parse(other); } catch (e) { src = {}; }
    }
    if (src && typeof src === 'object') {
      for (var k in src) {
        if (!Object.prototype.hasOwnProperty.call(src, k)) continue;
        if (typeof src[k] === 'function') continue;
        this.put(k, src[k]);
      }
    }
    return this;
  };
  return o;
}
"##,
        );
        code.push_str("var src = ");
        code.push_str(&escaped_src);
        code.push_str(";\nvar __sourceKey = ");
        code.push_str(&escaped_key);
        code.push_str(
            r##";
var source = (function(){
  var base = {};
  try { base = JSON.parse(src) || {}; } catch (e) { base = {}; }
  if (!base.bookSourceUrl) base.bookSourceUrl = __sourceKey;
  base.getKey = function() { return String(base.bookSourceUrl || __sourceKey || ''); };
  base.getLoginHeader = function() {
    return (typeof __legado_lc_get_login_header === 'function')
      ? (__legado_lc_get_login_header() || '') : '';
  };
  base.getLoginHeaderMap = function() {
    var h = this.getLoginHeader();
    if (!h) return {};
    try { return JSON.parse(h); } catch (e) { return { Cookie: h }; }
  };
  base.putLoginHeader = function(h) {
    if (typeof __legado_lc_put_login_header === 'function') {
      __legado_lc_put_login_header(String(h == null ? '' : h));
    }
  };
  base.getHeaderMap = function(hasLogin) {
    var raw = '{}';
    if (typeof __legado_lc_source_header_map === 'function') {
      raw = __legado_lc_source_header_map(!!hasLogin) || '{}';
    }
    try { return __wrapHeaderMap(JSON.parse(raw)); } catch (e) { return __wrapHeaderMap({}); }
  };
  return base;
})();
if (typeof __legado_set_ajax_ctx === 'function') {
  var __lh = (typeof __legado_lc_get_login_header === 'function')
    ? (__legado_lc_get_login_header() || '') : '';
  __legado_set_ajax_ctx(src, __lh);
}
if (typeof java !== 'undefined') {
  java.getHeaderMap = function() {
    var raw = '{}';
    if (typeof __legado_lc_header_map_json === 'function') {
      raw = __legado_lc_header_map_json() || '{}';
    }
    try { return __wrapHeaderMap(JSON.parse(raw)); } catch (e) { return __wrapHeaderMap({}); }
  };
  java.initUrl = function() {
    if (typeof __legado_lc_init_url === 'function') __legado_lc_init_url();
  };
  java.getStrResponse = function(_jsStr, _sourceRegex) {
    var raw = '{}';
    if (typeof __legado_lc_get_str_response === 'function') {
      raw = __legado_lc_get_str_response() || '{}';
    }
    var o = {};
    try { o = JSON.parse(raw) || {}; } catch (e) { o = {}; }
    return new __StrResponse(o.body || '', o.url || '', o.code);
  };
  java.startBrowserAwait = function(url, title, refetchAfterSuccess, html) {
    var refetch = (arguments.length < 3) ? true : !!refetchAfterSuccess;
    var hasHtml = arguments.length >= 4 && html !== null && html !== undefined;
    var raw = __legado_lc_start_browser(
      String(url == null ? '' : url),
      String(title == null ? '' : title),
      refetch,
      hasHtml,
      hasHtml ? String(html) : ''
    );
    var o = {};
    try { o = JSON.parse(raw) || {}; } catch (e) { o = {}; }
    return new __StrResponse(o.body || '', o.url || '', o.code);
  };
  if (typeof java.connect !== 'function') {
    java.connect = function(url) {
      var b = '';
      if (typeof __legado_java_ajax === 'function') {
        try { b = __legado_java_ajax(String(url == null ? '' : url)) || ''; } catch (e) { b = ''; }
      }
      return new __StrResponse(b, url, 200);
    };
  }
}
"##,
        );
        code.push_str("var result = new __StrResponse(");
        code.push_str(&escaped_body);
        code.push_str(", ");
        code.push_str(&escaped_url);
        code.push_str(", 200);\n");
        code.push_str(script);
        let v: Value = ctx
            .eval(code.as_bytes())
            .catch(&ctx)
            .map_err(|e| format_caught_err("loginCheckJs 失败", e))?;
        let v = if v.is_undefined() || v.is_null() {
            ctx.globals().get::<_, Value>("result").unwrap_or(v)
        } else {
            v
        };
        let (body_out, url_out) = normalize_login_check_pair(&ctx, v, request_url)?;
        Ok::<_, String>((body_out, url_out))
    });

    let login_header = LOGIN_CHECK_CTX.with(|c| {
        let dirty = c
            .borrow()
            .as_ref()
            .map(|x| x.login_header_dirty)
            .unwrap_or(false);
        let h = c
            .borrow()
            .as_ref()
            .map(|x| x.login_header.clone())
            .unwrap_or_default();
        *c.borrow_mut() = None;
        if dirty && !h.is_empty() {
            Some(h)
        } else {
            None
        }
    });

    let (body_out, url_out) = result?;
    Ok(LoginCheckResult {
        body: body_out,
        url: url_out,
        login_header,
    })
}

fn normalize_login_check_pair<'js>(
    ctx: &Ctx<'js>,
    v: Value<'js>,
    fallback_url: &str,
) -> Result<(String, String), String> {
    if v.is_null() || v.is_undefined() {
        return Ok((String::new(), fallback_url.to_string()));
    }
    if v.is_string() {
        return Ok((value_to_string(ctx, v)?, fallback_url.to_string()));
    }
    if let Some(obj) = v.as_object() {
        let mut body = String::new();
        let mut url = fallback_url.to_string();
        if let Ok(s) = obj.get::<_, String>("_body") {
            body = s;
        } else if let Ok(func) = obj.get::<_, Function>("body") {
            let out: Value = func
                .call(())
                .map_err(|e| format!("loginCheckJs result.body() 失败: {e}"))?;
            body = value_to_string(ctx, out)?;
        } else if let Ok(s) = obj.get::<_, String>("body") {
            body = s;
        }
        if let Ok(s) = obj.get::<_, String>("_url") {
            if !s.is_empty() {
                url = s;
            }
        } else if let Ok(func) = obj.get::<_, Function>("url") {
            if let Ok(out) = func.call::<(), Value>(()) {
                let s = value_to_string(ctx, out).unwrap_or_default();
                if !s.is_empty() {
                    url = s;
                }
            }
        }
        if !body.is_empty() || obj.get::<_, String>("_body").is_ok() {
            return Ok((body, url));
        }
        if let Ok(func) = obj.get::<_, Function>("toString") {
            if let Ok(out) = func.call::<(), Value>(()) {
                if out.is_string() {
                    return Ok((value_to_string(ctx, out)?, url));
                }
            }
        }
    }
    Ok((value_to_string(ctx, v)?, fallback_url.to_string()))
}

/// 对齐 Jingshiro `WebBook.getChapterListAwait`：目录刷新前执行 `ruleToc.preUpdateJs`。
/// 失败打日志，不阻断目录拉取。
pub fn run_pre_update_js(source: &crate::model::book_source::BookSource, book_url: &str) {
    let script = source.pre_update_js.trim();
    if script.is_empty() {
        return;
    }
    let base = if book_url.is_empty() {
        source.book_source_url.as_str()
    } else {
        book_url
    };
    let result = with_js_context(script, &source.js_lib, |ctx| {
        init_context(&ctx, &source.js_lib, base)?;
        AJAX_SOURCE_JSON.with(|r| *r.borrow_mut() = source.raw_json.clone());
        let book_inject = format!(
            "var book = {{ bookUrl: {}, name: '', author: '' }};\nvar result = '';\n",
            json_escape(book_url)
        );
        let mut code = book_inject;
        code.push_str("var src = ");
        code.push_str(&json_escape(&source.raw_json));
        code.push_str(
            ";\nif (typeof __legado_set_ajax_ctx === 'function') { __legado_set_ajax_ctx(src, ''); }\n",
        );
        code.push_str(script);
        ctx.eval::<Value, _>(code.as_bytes())
            .catch(&ctx)
            .map_err(|e| format_caught_err("preUpdateJs 失败", e))?;
        Ok::<(), String>(())
    });
    if let Err(e) = result {
        eprintln!("[preUpdateJs] 执行失败（继续拉目录）: {e}");
    }
}

/// 提取 `<js>...</js>` 内脚本
pub fn extract_js_block(rule: &str) -> Option<String> {
    let lower = rule.to_ascii_lowercase();
    let start = lower.find("<js>")?;
    let content_start = start + 4;
    let relative_end = lower[content_start..].find("</js>")?;
    let end = content_start + relative_end;
    Some(rule[content_start..end].to_string())
}

/// JavaScript `String(value)` semantics used by AnalyzeRule.getString.
fn value_to_js_string<'js>(ctx: &Ctx<'js>, v: Value<'js>) -> Result<String, String> {
    if v.is_null() || v.is_undefined() {
        return Ok(String::new());
    }
    if v.is_string() || v.is_number() || v.is_bool() {
        return value_to_string(ctx, v);
    }
    if v.is_array() {
        let array: Array<'js> = v.get().map_err(|e| format!("JS 数组转换失败: {e}"))?;
        let mut values = Vec::with_capacity(array.len());
        for item in array.iter::<Value<'js>>() {
            values.push(value_to_js_string(
                ctx,
                item.map_err(|e| format!("JS 数组读取失败: {e}"))?,
            )?);
        }
        return Ok(values.join(","));
    }
    if v.is_object() {
        return Ok("[object Object]".to_string());
    }
    value_to_string(ctx, v)
}

/// 规则是否含 `<js>` 块
pub fn contains_js_block(rule: &str) -> bool {
    extract_js_block(rule).is_some()
}

/// 提取 `<js>...</js>` 之后的 CSS/链式规则部分
pub fn css_suffix_after_js(rule: &str) -> &str {
    let lower = rule.to_ascii_lowercase();
    if let Some(end) = lower.find("</js>") {
        rule[end + 5..].trim()
    } else {
        rule.trim()
    }
}

fn json_escape(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn read_fixture_request(stream: &mut std::net::TcpStream) -> String {
        use std::io::Read;

        let mut request = Vec::new();
        let mut chunk = [0_u8; 4096];
        loop {
            let size = stream.read(&mut chunk).unwrap();
            if size == 0 {
                break;
            }
            request.extend_from_slice(&chunk[..size]);
            let Some(header_end) = request.windows(4).position(|window| window == b"\r\n\r\n")
            else {
                continue;
            };
            let header = String::from_utf8_lossy(&request[..header_end]);
            let content_length = header
                .lines()
                .find_map(|line| {
                    let (name, value) = line.split_once(':')?;
                    name.eq_ignore_ascii_case("content-length")
                        .then(|| value.trim().parse::<usize>().ok())
                        .flatten()
                })
                .unwrap_or(0);
            if request.len() >= header_end + 4 + content_length {
                break;
            }
        }
        String::from_utf8(request).unwrap()
    }

    struct BrowserHostReset;

    impl Drop for BrowserHostReset {
        fn drop(&mut self) {
            crate::browser_host::clear_test_host();
        }
    }

    #[test]
    #[serial_test::serial(source_browser_host)]
    fn start_browser_await_matches_two_three_and_four_argument_contracts() {
        use std::io::{Read, Write};
        use std::net::TcpListener;

        let _reset = BrowserHostReset;
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let url = format!("http://{}/verify", listener.local_addr().unwrap());
        let final_url = format!("http://{}/done", listener.local_addr().unwrap());
        let server = std::thread::spawn(move || {
            for (index, path) in ["/verify", "/done"].iter().enumerate() {
                let (mut stream, _) = listener.accept().unwrap();
                let mut request = [0_u8; 2048];
                let size = stream.read(&mut request).unwrap();
                let request = String::from_utf8_lossy(&request[..size]);
                assert!(request.starts_with(&format!("GET {path} ")));
                assert!(request.to_ascii_lowercase().contains("x-source: base"));
                if index == 0 {
                    stream
                        .write_all(
                            b"HTTP/1.1 302 Found\r\nLocation: /done\r\nContent-Length: 0\r\nConnection: close\r\n\r\n",
                        )
                        .unwrap();
                } else {
                    stream
                        .write_all(
                            b"HTTP/1.1 200 OK\r\nContent-Length: 9\r\nConnection: close\r\n\r\nrefetched",
                        )
                        .unwrap();
                }
            }
        });

        crate::browser_host::set_test_host({
            let expected_url = url.clone();
            move |request| {
                assert_eq!(request.source_key, "https://source.example");
                assert_eq!(request.url, expected_url);
                assert_eq!(request.title, "验证");
                assert!(request.html.is_none());
                assert!(request.refetch_after_success);
                assert_eq!(
                    request.headers.get("X-Source").map(String::as_str),
                    Some("base")
                );
                Ok(crate::api::SourceBrowserResponseDto {
                    final_url: "https://ignored.example/done".into(),
                    body: "ignored-dom".into(),
                })
            }
        });
        let source = serde_json::json!({
            "bookSourceUrl": "https://source.example",
            "header": {"X-Source": "base"},
            "loginCheckJs": format!("java.startBrowserAwait({}, '验证')", json_escape(&url)),
        })
        .to_string();
        let out = apply_login_check_js(&source, "before", &url, "GET", None, "UTF-8");
        assert_eq!(out.body, "refetched");
        assert_eq!(out.url, final_url);
        server.join().unwrap();

        crate::browser_host::set_test_host(|request| {
            assert!(!request.refetch_after_success);
            assert!(request.html.is_none());
            Ok(crate::api::SourceBrowserResponseDto {
                final_url: "https://source.example/verified".into(),
                body: "verified-dom".into(),
            })
        });
        let source = serde_json::json!({
            "bookSourceUrl": "https://source.example",
            "loginCheckJs": "var verified = java.startBrowserAwait('https://source.example/check', '验证', false); new __StrResponse(verified.body() + '|continued', verified.url(), verified.code())",
        })
        .to_string();
        let out = apply_login_check_js(
            &source,
            "before",
            "https://source.example/check",
            "GET",
            None,
            "UTF-8",
        );
        assert_eq!(out.body, "verified-dom|continued");
        assert_eq!(out.url, "https://source.example/verified");

        crate::browser_host::set_test_host(|request| {
            assert!(request.refetch_after_success);
            assert_eq!(request.html.as_deref(), Some("<html>seed</html>"));
            Ok(crate::api::SourceBrowserResponseDto {
                final_url: "https://source.example/ignored".into(),
                body: "ignored-dom".into(),
            })
        });
        let source = serde_json::json!({
            "bookSourceUrl": "https://source.example",
            "loginCheckJs": "java.startBrowserAwait('https://source.example/check', '验证', true, '<html>seed</html>')",
        })
        .to_string();
        let out = apply_login_check_js(
            &source,
            "before",
            "https://source.example/check",
            "GET",
            None,
            "UTF-8",
        );
        assert_eq!(out.body, "<html>seed</html>");
        assert_eq!(out.url, "https://source.example/check");
    }

    #[test]
    #[serial_test::serial(source_browser_host)]
    fn start_browser_await_rejects_urls_at_64_kib_without_calling_host() {
        use std::sync::atomic::{AtomicBool, Ordering};
        use std::sync::Arc;

        let _reset = BrowserHostReset;
        let called = Arc::new(AtomicBool::new(false));
        crate::browser_host::set_test_host({
            let called = called.clone();
            move |_request| {
                called.store(true, Ordering::SeqCst);
                Ok(crate::api::SourceBrowserResponseDto {
                    final_url: String::new(),
                    body: String::new(),
                })
            }
        });
        let long_url = format!("https://example.com/{}", "a".repeat(64 * 1024));
        let source = serde_json::json!({
            "bookSourceUrl": "https://source.example",
            "loginCheckJs": format!("java.startBrowserAwait({}, '验证')", json_escape(&long_url)),
        })
        .to_string();
        let out = apply_login_check_js(
            &source,
            "original",
            "https://source.example/original",
            "GET",
            None,
            "UTF-8",
        );
        assert_eq!(out.body, "original");
        assert!(!called.load(Ordering::SeqCst));

        let utf16_short_url = format!("https://example.com/{}", "界".repeat(22_000));
        assert!(utf16_short_url.len() >= 64 * 1024);
        assert!(utf16_short_url.encode_utf16().count() < 64 * 1024);
        let source = serde_json::json!({
            "bookSourceUrl": "https://source.example",
            "loginCheckJs": format!(
                "java.startBrowserAwait({}, '验证', false)",
                json_escape(&utf16_short_url)
            ),
        })
        .to_string();
        let out = apply_login_check_js(
            &source,
            "original",
            "https://source.example/original",
            "GET",
            None,
            "UTF-8",
        );
        assert!(called.load(Ordering::SeqCst));
        assert_eq!(out.url, utf16_short_url);
    }

    #[test]
    fn js_block_markers_are_case_insensitive_and_keep_suffix() {
        let rule = "<JS>result + '!'</Js>\n.book-list";
        assert!(contains_js_block(rule));
        assert_eq!(extract_js_block(rule).as_deref(), Some("result + '!'"));
        assert_eq!(css_suffix_after_js(rule), ".book-list");
    }

    #[test]
    fn run_simple_js_transform() {
        let out = run_with_result("result + suffix", "hello", "var suffix = '!'", "").unwrap();
        assert_eq!(out, "hello!");
    }

    #[test]
    fn quickjs_interrupts_infinite_loop_with_classified_error() {
        let started = Instant::now();
        let err = run_eval_script("while (true) {}", "", "").expect_err("无限循环必须被中断");
        assert!(err.contains("JS 执行失败"), "错误应保留 JS 分类前缀: {err}");
        assert!(
            err.contains("超时") || err.contains("interrupted"),
            "错误应明确表示 QuickJS 被中断: {err}"
        );
        assert!(
            started.elapsed() < Duration::from_secs(10),
            "中断不应明显超过 5 秒预算: {:?}",
            started.elapsed()
        );
    }

    #[test]
    fn quickjs_rejects_script_input_over_limit() {
        let script = "x".repeat(MAX_JS_INPUT_BYTES + 1);
        let err = run_eval_script(&script, "", "").expect_err("超大脚本必须被拒绝");
        assert!(err.contains("JS 执行失败"), "错误应保留 JS 分类前缀: {err}");
        assert!(
            err.contains("脚本输入超过"),
            "错误应说明脚本大小门禁: {err}"
        );
    }

    #[test]
    fn string_conversion_of_js_array_matches_rhino_array_to_string() {
        let out = run_with_result_as_string("['第一项', '第二项']", "", "", "").unwrap();
        assert_eq!(out, "第一项,第二项");
    }

    #[test]
    fn run_jsoup_parse() {
        let script = r#"
var html = String(result);
var doc = Packages.org.jsoup.Jsoup.parse(html);
var a = doc.selectFirst('a');
a ? a.text() : '';
"#;
        let out = run_html_js(script, "<a href='/1'>书名</a>", "", "").unwrap();
        assert_eq!(out, "书名");
    }

    #[test]
    fn run_jsoup_select_id() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('#nr');
el ? el.text() : '';
"#;
        let html = r#"<article id="nr">正文内容</article>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert_eq!(out, "正文内容");
    }

    #[test]
    fn run_jsoup_select_tag_id() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('article#nr');
el ? el.text() : '';
"#;
        let html = r#"<div><article id="nr">第一章</article></div>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert_eq!(out, "第一章");
    }

    #[test]
    fn run_jsoup_select_attr_equals() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('[id=nr]');
el ? el.text() : '';
"#;
        let html = r#"<article id="nr">属性选择</article>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert_eq!(out, "属性选择");
    }

    #[test]
    fn run_jsoup_html_method() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('article#nr');
el ? el.html() : '';
"#;
        let html = r#"<article id="nr"><p>段落</p></article>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert!(out.contains("<p>段落</p>"), "html() 应含 inner HTML: {out}");
    }

    #[test]
    fn run_jsoup_7565_content_script() {
        let script = r#"
var html = String(result);
var doc = Packages.org.jsoup.Jsoup.parse(html);
var nr = doc.selectFirst('article#nr');
var lines = [];
if (nr) {
    var rawHtml = String(nr.html());
    rawHtml = rawHtml.replace(/<br\s*\/?>/gi, '\n');
    var parts = rawHtml.split('\n');
    for (var i = 0; i < parts.length; i++) {
        var line = parts[i].replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').replace(/\u00a0/g, ' ').trim();
        if (line) {
            lines.push(line);
        }
    }
}
lines.join('\n');
"#;
        let html = r#"
<html><body>
<article id="nr">
<p>第一章 开端</p><br/>
<p>这是测试正文段落，字数需要足够多以验证清洗逻辑正常工作。</p>
<p>第二段继续补充内容，确保 join 后超过一百个字符。</p>
</article>
</body></html>
"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert!(out.len() > 100, "7565 脚本输出过短: {} chars", out.len());
        assert!(out.contains("测试正文"), "应含正文: {out}");
    }

    /// 笔书网移动站：正文是文本节点与 `<br/>` 交错；若 html() 先拼全部 text 再拼子节点，
    /// 整章会落在一行并被「本章未完.*继续阅读」过滤成空。
    #[test]
    fn run_jsoup_preserves_br_text_order_for_7565_filter() {
        let script = r#"
var html = String(result);
var doc = Packages.org.jsoup.Jsoup.parse(html);
var nr = doc.selectFirst('article#nr');
var lines = [];
if (nr) {
    var rawHtml = String(nr.html());
    rawHtml = rawHtml.replace(/<br\s*\/?>/gi, '\n');
    var parts = rawHtml.split('\n');
    for (var i = 0; i < parts.length; i++) {
        var line = parts[i].replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').replace(/\u00a0/g, ' ').trim();
        if (line) {
            if (/最新网址|m\.biqukun|本章未完.*继续阅读/.test(line)) continue;
            lines.push(line);
        }
    }
    if (lines.length > 0 && /^第\d+章/.test(lines[0])) {
        lines.shift();
    }
}
lines.join('\n');
"#;
        let html = r#"
<html><body>
<article id="nr">&nbsp;&nbsp;&nbsp;&nbsp;第5章 标题 (第1/3页)<br /><br />旁白：这是正文第一段足够长。<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;这是正文第二段，继续补充内容避免过短。<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;本章未完，请翻下一页继续阅读。</article>
</body></html>
"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert!(out.contains("正文第一段"), "应保留正文: {out}");
        assert!(out.contains("正文第二段"), "应保留分段: {out}");
        assert!(!out.contains("本章未完"), "应过滤未完提示: {out}");
        assert!(!out.contains("第5章"), "应去掉章名行: {out}");
    }

    #[test]
    fn run_jsoup_html_is_inner_with_ordered_br() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('article#nr');
el ? el.html() : '';
"#;
        let html = r#"<article id="nr">甲<br />乙</article>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert!(!out.contains("<article"), "html() 应为 inner: {out}");
        assert!(
            out.contains("甲")
                && out.contains("乙")
                && out.find("甲").unwrap() < out.find("乙").unwrap(),
            "文本与 br 须保序: {out}"
        );
        assert!(
            out.find("甲").unwrap() < out.to_lowercase().find("br").unwrap()
                && out.to_lowercase().find("br").unwrap() < out.find("乙").unwrap(),
            "顺序应为 甲 / br / 乙: {out}"
        );
    }

    #[test]
    fn run_jsoup_bilibili_show_rule_dom_mutations() {
        let script = r#"
var aly = new JavaImporter(Packages.org.jsoup.nodes.Element,
Packages.org.jsoup.Jsoup,
Packages.org.jsoup.select.Elements);
with (aly) {
  result = Jsoup.parse(result);
  result.select("img").remove();
  let bs = '<br><br>📺<br>';
  result.select(".media-card-image").before(bs);
  result.select(".video-list .bili-video-card").before(bs);
  result.select("a:has(button)").after("　");
  let links = result.select("a");
  for (link of links) {
    let h3 = link.selectFirst("h3");
    if (h3 != null) {
      let content = h3.text();
      link.select("h3").remove();
      let H3 = new Element("h3")
        .appendChild(new Element("a").attr("href", link.attr("href")).text(content))
        .appendText("　");
      link.replaceWith(H3);
    }
  }
}
result.html();
"#;
        let html = r#"
<div class="search-page">
  <img src="cover.jpg" />
  <div class="media-card-image">封面</div>
  <div class="video-list"><div class="bili-video-card">视频卡片</div></div>
  <a href="bilibili://space/1"><button>关注</button></a>
  <a href="bilibili://video/BV1"><h3>测试视频</h3><span>简介</span></a>
</div>
"#;
        let out = run_html_js(script, html, "", "").unwrap();

        assert!(!out.contains("<img"), "img 应被移除: {out}");
        assert_eq!(
            out.matches('📺').count(),
            2,
            "两处卡片前均应插入标记: {out}"
        );
        assert!(
            out.contains("</button></a>　"),
            "含 button 的链接后应插入空格: {out}"
        );
        assert!(
            out.contains("<h3><a href=\"bilibili://video/BV1\">测试视频</a>　</h3>"),
            "视频链接应替换为新建 h3 节点: {out}"
        );
        assert!(
            !out.contains("<span>简介</span>"),
            "原链接应被整体替换: {out}"
        );
    }

    #[test]
    fn run_jsoup_han_dictionary_remove_rule() {
        let script = r##"
var jsoup = org.jsoup.Jsoup.parse(result);
jsoup.select("script,#header,#footer,#page-share,.mslide,.title,#dictHcBtn,#dictHcBtnTop,#dictHc,#dictHc,#dictHcSettingArea,#dictHcClosetip").remove();
jsoup.select("#cy").html();
"##;
        let html = r#"
<html><body>
  <header id="header">页头</header>
  <div id="cy">
    <p>中文释义</p><script>remove me</script><span class="title">也应删除</span>
    <span class="keep">保留内容</span>
  </div>
  <footer id="footer">页尾</footer>
</body></html>
"#;
        let out = run_html_js(script, html, "", "").unwrap();

        assert!(out.contains("<p>中文释义</p>"), "应保留释义: {out}");
        assert!(out.contains("<span class=\"keep\">保留内容</span>"));
        assert!(!out.contains("remove me"), "script 应被删除: {out}");
        assert!(!out.contains("也应删除"), ".title 应被删除: {out}");
    }

    #[test]
    fn run_jsoup_youdao_id_selectors_keep_sibling_ranges_separate() {
        let script = r#"
let j = org.jsoup.Jsoup.parse(result);
let yw = j.select('#inputText').text();
let fy = j.select('#translateResult').text();
result = '原文：<br>'+yw+'<br>翻译：<br>'+fy;
"#;
        let html = r#"
<html><body>
  <div id="inputText">hello world</div>
  <div id="translateResult">你好世界</div>
</body></html>
"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert_eq!(out, "原文：<br>hello world<br>翻译：<br>你好世界");
    }

    /// 可乐小说 searchUrl：AES-256-CBC + encryptBase64（Hutool/Legado java.createSymmetricCrypto）
    #[test]
    fn run_create_symmetric_crypto_aes_cbc_encrypt_base64() {
        let script = r#"
var keyStr='lzxHpH8PLGXcrCIQ';
var key32=keyStr;
while(key32.length < 32){key32 += String.fromCharCode(0);}
var crypto=java.createSymmetricCrypto('AES/CBC/PKCS5Padding',key32,keyStr);
crypto.encryptBase64(key);
"#;
        let out = run_search_js(script, "重生之", "", "https://www.rrssk.com/", 1).unwrap();
        assert_eq!(out, "breUSzu0dAfgrP33wtpsvg==");
    }

    #[test]
    fn run_kele_search_url_template_js() {
        let template = r#"<js>var keyStr='lzxHpH8PLGXcrCIQ';var key32=keyStr;while(key32.length < 32){key32 += String.fromCharCode(0);}var crypto=java.createSymmetricCrypto('AES/CBC/PKCS5Padding',key32,keyStr);var enc=crypto.encryptBase64(key);var url='https://www.rrssk.com/k-'+enc+'.html';if(page>1)url='https://www.rrssk.com/k-'+enc+'-'+page+'.html';url</js>"#;
        let out = run_url_template_js(template, "重生之", "", "https://www.rrssk.com/", 1).unwrap();
        assert_eq!(out, "https://www.rrssk.com/k-breUSzu0dAfgrP33wtpsvg==.html");
        let out2 =
            run_url_template_js(template, "重生之", "", "https://www.rrssk.com/", 2).unwrap();
        assert_eq!(
            out2,
            "https://www.rrssk.com/k-breUSzu0dAfgrP33wtpsvg==-2.html"
        );
    }

    #[test]
    fn java_ajax_binding_registered() {
        let out = run_eval_script(
            "typeof java.ajax === 'function' && typeof __legado_java_ajax === 'function' ? 'ok' : 'no'",
            "",
            "https://www.kelexs.com/",
        )
        .unwrap();
        assert_eq!(out, "ok");
    }

    #[test]
    fn java_ajax_ssrf_returns_empty() {
        let out = run_eval_script("java.ajax('http://127.0.0.1/')", "", "").unwrap();
        assert_eq!(out, "");
    }

    #[test]
    fn java_ajax_fetches_loopback_get_and_resolves_relative_url() {
        use std::io::Write;
        use std::net::TcpListener;

        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let base_url = format!("http://{}", listener.local_addr().unwrap());
        let expected_referer = format!("{base_url}/book");
        let server = std::thread::spawn(move || {
            let (mut stream, _) = listener.accept().unwrap();
            let request = read_fixture_request(&mut stream);
            assert!(
                request.starts_with("GET /relative HTTP/1.1"),
                "请求={request}"
            );
            assert!(
                request.contains(&format!("Referer: {expected_referer}"))
                    || request.contains(&format!("referer: {expected_referer}")),
                "相对 URL 请求必须保留 baseUrl 作为 Referer: {request}"
            );
            stream
                .write_all(
                    b"HTTP/1.1 200 OK\r\nContent-Length: 12\r\nConnection: close\r\n\r\nloopback-get",
                )
                .unwrap();
        });

        let out =
            run_eval_script("java.ajax('/relative')", "", &format!("{base_url}/book")).unwrap();
        assert_eq!(out, "loopback-get");
        server.join().unwrap();
    }

    #[test]
    fn java_ajax_posts_analyze_url_body_and_headers_to_loopback_fixture() {
        use std::io::Write;
        use std::net::TcpListener;

        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let url = format!("http://{}/submit", listener.local_addr().unwrap());
        let server = std::thread::spawn(move || {
            let (mut stream, _) = listener.accept().unwrap();
            let request = read_fixture_request(&mut stream);
            assert!(
                request.starts_with("POST /submit HTTP/1.1"),
                "请求={request}"
            );
            assert!(
                request.lines().any(|line| {
                    line.split_once(':')
                        .map(|(name, value)| {
                            name.eq_ignore_ascii_case("x-test") && value.trim() == "fixture"
                        })
                        .unwrap_or(false)
                }),
                "请求头未传递: {request}"
            );
            assert!(request.ends_with("a=1&b=2"), "请求体未传递: {request}");
            stream
                .write_all(
                    b"HTTP/1.1 201 Created\r\nContent-Length: 13\r\nConnection: close\r\n\r\nloopback-post",
                )
                .unwrap();
        });

        let ajax_url = format!(
            "{url},{}",
            serde_json::json!({
                "method": "POST",
                "body": "a=1&b=2",
                "headers": {"X-Test": "fixture"}
            })
        );
        let script = format!("java.ajax({})", json_escape(&ajax_url));
        let out = run_eval_script(&script, "", "").unwrap();
        assert_eq!(out, "loopback-post");
        server.join().unwrap();
    }

    #[test]
    fn java_ajax_accepts_analyze_url_post_shape() {
        // 不发起真实外网：非法主机应被 SSRF 拦截并返回空串；同时验证 AnalyzeUrl 解析不 panic
        let out = run_eval_script(
            r#"java.ajax('http://127.0.0.1/login,{"method":"POST","body":"a=1","headers":{"X-Test":"1"}}')"#,
            "",
            "https://example.com/",
        )
        .unwrap();
        assert_eq!(out, "");
    }

    #[test]
    fn set_ajax_ctx_exposed() {
        let out = run_eval_script(
            "typeof __legado_set_ajax_ctx === 'function' ? 'ok' : 'no'",
            "",
            "",
        )
        .unwrap();
        assert_eq!(out, "ok");
    }

    #[test]
    fn java_base64_and_hex_helpers_match_dict_rule_usage() {
        let encoded = run_eval_script("java.base64Encode('测试')", "", "").unwrap();
        assert_eq!(encoded, "5rWL6K+V");
        let decoded = run_eval_script("java.hexDecodeToString('e6b58be8af95')", "", "").unwrap();
        assert_eq!(decoded, "测试");
        let unchanged = run_eval_script("java.hexDecodeToString('测试')", "", "").unwrap();
        assert_eq!(unchanged, "测试");
    }

    #[test]
    fn java_importer_exposes_jayway_jsonpath() {
        let script = r#"
var aly = new JavaImporter(Packages.com.jayway.jsonpath);
var value = null;
with (aly) {
  var rr = JsonPath.using(
    Configuration.builder().options(Option.SUPPRESS_EXCEPTIONS).build()
  ).parse(result);
  value = rr.read('$.data.pinyin');
}
value;
"#;
        let out =
            run_with_result_as_string(script, r#"{"data":{"pinyin":"ce shi"}}"#, "", "").unwrap();
        assert_eq!(out, "ce shi");
    }

    #[test]
    fn jayway_jsonpath_static_read_and_global_com_match_default_rules() {
        let out = run_with_book_as_string(
            "com.jayway.jsonpath.JsonPath.read(result, '$.data.data[*]')[0].cover",
            r#"{"data":{"data":[{"cover":"https://cover.example/a.jpg"}]}}"#,
            "",
            "",
            "书名",
            "作者",
        )
        .unwrap();
        assert_eq!(out, "https://cover.example/a.jpg");
    }

    #[test]
    fn jayway_jsonpath_default_pinyin_path_stays_array() {
        let script = r#"
var aly = new JavaImporter(Packages.com.jayway.jsonpath);
var rr = JsonPath.using(
  Configuration.builder().options(Option.SUPPRESS_EXCEPTIONS).build()
).parse(result);
JSON.stringify(rr.read('$.data..comprehensiveDefinition[*].pinyin'));
"#;
        let out = run_with_result_as_string(
            script,
            r#"{"data":{"comprehensiveDefinition":[{"pinyin":"ce4"}]}}"#,
            "",
            "",
        )
        .unwrap();
        assert_eq!(out, r#"["ce4"]"#);
    }

    #[test]
    fn jayway_jsonpath_default_cixing_path_keeps_nested_array() {
        let script = r#"
var aly = new JavaImporter(Packages.com.jayway.jsonpath);
var rr = JsonPath.using(
  Configuration.builder().options(Option.SUPPRESS_EXCEPTIONS).build()
).parse(result);
JSON.stringify(rr.read('$.data..comprehensiveDefinition[0].basicDefinition[*]cixing'));
"#;
        let out = run_with_result_as_string(
            script,
            r#"{"data":{"comprehensiveDefinition":[{"basicDefinition":[{"cixing":["动"]}]}]}}"#,
            "",
            "",
        )
        .unwrap();
        assert_eq!(out, r#"[["动"]]"#);
    }

    #[test]
    #[serial_test::serial(js_cache)]
    fn shared_cache_across_js_runtimes() {
        let _ = reset_cache();
        let put = run_with_result(
            "cache.put('kelexs_key','abc123',86400); cache.get('kelexs_key')",
            "",
            "",
            "https://www.kelexs.com/",
        )
        .unwrap();
        assert_eq!(put, "abc123");
        // 新 Runtime 仍能读到
        let got =
            run_with_result("cache.get('kelexs_key')", "", "", "https://www.kelexs.com/").unwrap();
        assert_eq!(got, "abc123");
        let _ = reset_cache();
        assert_eq!(
            run_with_result("cache.get('kelexs_key')", "", "", "").unwrap(),
            ""
        );
    }
}
