use rquickjs::{
    CatchResultExt, CaughtError, Context, Ctx, Exception, Function, Runtime, Value,
};
use std::cell::RefCell;

const STDLIB: &str = include_str!("js_assets/stdlib.js");
const JSOUP: &str = include_str!("js_assets/jsoup.js");

thread_local! {
    /// 当前 JS 执行的 `baseUrl`，供 `java.ajax` 作 Referer
    static AJAX_REFERER: RefCell<String> = const { RefCell::new(String::new()) };
    /// 书源 JSON（含 header），供 ajax 合并请求头 — 对齐 AnalyzeUrl(source=…)
    static AJAX_SOURCE_JSON: RefCell<String> = const { RefCell::new(String::new()) };
    /// 登录头 JSON / Cookie 串
    static AJAX_LOGIN_HEADER: RefCell<String> = const { RefCell::new(String::new()) };
}

/// 将 QuickJS CaughtError 展开为可读信息（避免仅见 "Exception generated by QuickJS"）
fn format_caught_err(prefix: &str, err: CaughtError<'_>) -> String {
    match err {
        CaughtError::Exception(ex) => {
            let msg = ex.message().unwrap_or_default();
            let stack = ex.stack().unwrap_or_default();
            if !msg.is_empty() && !stack.is_empty() {
                format!("{prefix}: {msg}\n{stack}")
            } else if !msg.is_empty() {
                format!("{prefix}: {msg}")
            } else {
                format!("{prefix}: {ex}")
            }
        }
        CaughtError::Value(v) => format!("{prefix}: {v:?}"),
        CaughtError::Error(e) => format!("{prefix}: {e}"),
    }
}

fn register_host_apis(ctx: &Ctx<'_>) -> Result<(), String> {
    let encrypt = Function::new(ctx.clone(), {
        move |ctx: Ctx<'_>, transformation: String, key: String, iv: String, data: String| {
            match super::js_crypto::encrypt_base64(&transformation, &key, &iv, &data) {
                Ok(s) => Ok(s),
                Err(e) => Err(Exception::throw_message(&ctx, &format!("AES encrypt 失败: {e}"))),
            }
        }
    })
    .map_err(|e| format!("注册 AES encrypt 失败: {e}"))?;
    ctx.globals()
        .set("__legado_aes_encrypt_b64", encrypt)
        .map_err(|e| format!("注入 AES encrypt 失败: {e}"))?;

    let decrypt = Function::new(ctx.clone(), {
        move |ctx: Ctx<'_>, transformation: String, key: String, iv: String, data: String| {
            match super::js_crypto::decrypt_str(&transformation, &key, &iv, &data) {
                Ok(s) => Ok(s),
                Err(e) => Err(Exception::throw_message(&ctx, &format!("AES decrypt 失败: {e}"))),
            }
        }
    })
    .map_err(|e| format!("注册 AES decrypt 失败: {e}"))?;
    ctx.globals()
        .set("__legado_aes_decrypt_str", decrypt)
        .map_err(|e| format!("注入 AES decrypt 失败: {e}"))?;

    // Jingshiro JsExtensions.ajax — 同步拉页面（失败返回空串，调用方常 try/catch）
    let ajax = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, url: String| -> Result<String, rquickjs::Error> {
            let referer = AJAX_REFERER.with(|r| r.borrow().clone());
            let source_json = AJAX_SOURCE_JSON.with(|r| r.borrow().clone());
            let login_header = AJAX_LOGIN_HEADER.with(|r| r.borrow().clone());
            match crate::http::client::ajax_blocking(
                &url,
                if referer.is_empty() {
                    None
                } else {
                    Some(referer.as_str())
                },
                if source_json.is_empty() {
                    None
                } else {
                    Some(source_json.as_str())
                },
                if login_header.is_empty() {
                    None
                } else {
                    Some(login_header.as_str())
                },
            ) {
                Ok(body) => Ok(body),
                Err(_) => Ok(String::new()),
            }
        }
    })
    .map_err(|e| format!("注册 java.ajax 失败: {e}"))?;
    ctx.globals()
        .set("__legado_java_ajax", ajax)
        .map_err(|e| format!("注入 java.ajax 失败: {e}"))?;

    // 登录/源脚本注入 ajax 上下文（书源 header + 登录头）
    let set_ajax_ctx = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, source_json: String, login_header: String| {
            AJAX_SOURCE_JSON.with(|r| *r.borrow_mut() = source_json);
            AJAX_LOGIN_HEADER.with(|r| *r.borrow_mut() = login_header);
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 set_ajax_ctx 失败: {e}"))?;
    ctx.globals()
        .set("__legado_set_ajax_ctx", set_ajax_ctx)
        .map_err(|e| format!("注入 set_ajax_ctx 失败: {e}"))?;

    let cache_put = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, key: String, value: String, seconds: i64| {
            super::js_cache::put(&key, &value, seconds);
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 cache.put 失败: {e}"))?;
    ctx.globals()
        .set("__legado_cache_put", cache_put)
        .map_err(|e| format!("注入 cache.put 失败: {e}"))?;

    let cache_get = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, key: String| Ok::<String, rquickjs::Error>(super::js_cache::get(&key))
    })
    .map_err(|e| format!("注册 cache.get 失败: {e}"))?;
    ctx.globals()
        .set("__legado_cache_get", cache_get)
        .map_err(|e| format!("注入 cache.get 失败: {e}"))?;

    let cache_delete = Function::new(ctx.clone(), {
        move |_ctx: Ctx<'_>, key: String| {
            super::js_cache::delete(&key);
            Ok::<(), rquickjs::Error>(())
        }
    })
    .map_err(|e| format!("注册 cache.delete 失败: {e}"))?;
    ctx.globals()
        .set("__legado_cache_delete", cache_delete)
        .map_err(|e| format!("注入 cache.delete 失败: {e}"))?;

    Ok(())
}

fn init_context(ctx: &Ctx<'_>, js_lib: &str, base_url: &str) -> Result<(), String> {
    AJAX_REFERER.with(|r| {
        *r.borrow_mut() = base_url.to_string();
    });
    AJAX_SOURCE_JSON.with(|r| r.borrow_mut().clear());
    AJAX_LOGIN_HEADER.with(|r| r.borrow_mut().clear());
    register_host_apis(ctx)?;
    ctx.eval::<(), _>(STDLIB.as_bytes())
        .catch(ctx)
        .map_err(|e| format_caught_err("JS 标准库加载失败", e))?;
    ctx.eval::<(), _>(JSOUP.as_bytes())
        .catch(ctx)
        .map_err(|e| format_caught_err("Jsoup 兼容层加载失败", e))?;
    let base_code = format!("baseUrl = {};", json_escape(base_url));
    ctx.eval::<(), _>(base_code.as_bytes())
        .catch(ctx)
        .map_err(|e| format_caught_err("baseUrl 注入失败", e))?;
    if !js_lib.trim().is_empty() {
        ctx.eval::<(), _>(js_lib.as_bytes())
            .catch(ctx)
            .map_err(|e| format_caught_err("jsLib 加载失败", e))?;
    }
    Ok(())
}

fn value_to_string<'js>(ctx: &Ctx<'js>, v: Value<'js>) -> Result<String, String> {
    if v.is_null() || v.is_undefined() {
        return Ok(String::new());
    }
    if v.is_string() {
        if let Some(s) = v.as_string() {
            return s
                .to_string()
                .map_err(|e| format!("JS 字符串转换失败: {e}"));
        }
        return Ok(String::new());
    }
    if v.is_number() {
        return Ok(v
            .as_number()
            .map(|n| n.to_string())
            .unwrap_or_default());
    }
    if v.is_bool() {
        return Ok(v
            .as_bool()
            .map(|b| b.to_string())
            .unwrap_or_default());
    }
    match ctx.json_stringify(v).map_err(|e| format!("JS JSON 序列化失败: {e}"))? {
        Some(s) => s
            .to_string()
            .map_err(|e| format!("JS JSON 字符串转换失败: {e}")),
        None => Ok(String::new()),
    }
}

/// 新一轮书源操作前清空跨 Runtime 的书源 `cache`
pub fn reset_cache() -> Result<(), String> {
    super::js_cache::clear();
    Ok(())
}

/// 执行裸 JS 脚本（搜索 @js: / URL 模板用）
pub fn run_eval_script(script: &str, js_lib: &str, base_url: &str) -> Result<String, String> {
    let rt = Runtime::new().map_err(|e| format!("JS Runtime 失败: {e}"))?;
    let ctx = Context::full(&rt).map_err(|e| format!("JS Context 失败: {e}"))?;
    ctx.with(|ctx| {
        init_context(&ctx, js_lib, base_url)?;
        let v: Value = ctx
            .eval(script.as_bytes())
            .catch(&ctx)
            .map_err(|e| format_caught_err("JS 执行失败", e))?;
        value_to_string(&ctx, v)
    })
}

/// `@js:` 搜索 URL 脚本
pub fn run_search_js(
    script: &str,
    keyword: &str,
    js_lib: &str,
    base_url: &str,
    page: i32,
) -> Result<String, String> {
    let base_host = json_escape(&crate::http::client::base_url(base_url));
    let code = format!(
        "var key = {};\nvar page = {};\nvar baseUrl = {};\nfunction Base() {{ return {}; }}\n{}\n{}",
        json_escape(keyword),
        page,
        json_escape(base_url),
        base_host,
        js_lib,
        script
    );
    run_eval_script(&code, "", base_url)
}

/// 含 `<js>` 的 URL 模板
pub fn run_url_template_js(
    template: &str,
    keyword: &str,
    js_lib: &str,
    base_url: &str,
    page: i32,
) -> Result<String, String> {
    let script = extract_js_block(template).ok_or("URL 模板无 <js> 块")?;
    let base_host = json_escape(&crate::http::client::base_url(base_url));
    let code = format!(
        "var result = {{\"articleid\":\"\"}};\nvar baseUrl = {};\nvar articleid = '';\nvar key = {};\nvar page = {};\nfunction J(obj) {{ return obj; }}\nfunction Base() {{ return {}; }}\n{}\n{}",
        json_escape(base_url),
        json_escape(keyword),
        page,
        base_host,
        js_lib,
        script
    );
    run_eval_script(&code, "", base_url)
}

/// 执行 Legado `<js>...</js>` 脚本，`result` 为输入数据
pub fn run_with_result(
    script: &str,
    result: &str,
    js_lib: &str,
    base_url: &str,
) -> Result<String, String> {
    run_with_result_opts(script, result, js_lib, base_url, None)
}

/// 同 [`run_with_result`]，可注入 `book.bookUrl`（对齐 Jingshiro AnalyzeRule + Book）
pub fn run_with_result_opts(
    script: &str,
    result: &str,
    js_lib: &str,
    base_url: &str,
    book_url: Option<&str>,
) -> Result<String, String> {
    let rt = Runtime::new().map_err(|e| format!("JS Runtime 失败: {e}"))?;
    let ctx = Context::full(&rt).map_err(|e| format!("JS Context 失败: {e}"))?;
    ctx.with(|ctx| {
        init_context(&ctx, js_lib, base_url)?;
        let escaped = serde_json::to_string(result).unwrap_or_else(|_| "\"\"".to_string());
        let book_url = book_url.unwrap_or(base_url);
        let book_inject = format!(
            "var book = {{ bookUrl: {}, name: '', author: '' }};\n",
            json_escape(book_url)
        );
        let code = format!(
            "{book_inject}legadoResult = {escaped}; var result = typeof legadoResult === 'string' ? legadoResult : JSON.stringify(legadoResult);\n{script}"
        );
        let v: Value = ctx
            .eval(code.as_bytes())
            .catch(&ctx)
            .map_err(|e| format_caught_err("JS 执行失败", e))?;
        value_to_string(&ctx, v)
    })
}

/// 纯 property 规则名（如 `chaptername` / `chapterurl`），无 CSS/`@`
pub fn is_plain_property_rule(rule: &str) -> bool {
    let r = rule.trim();
    !r.is_empty()
        && !r.contains('@')
        && !r.contains('<')
        && !r.contains('.')
        && !r.contains('#')
        && !r.contains(' ')
        && !r.contains(':')
        && r.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// 对 HTML 执行 `<js>` 脚本并返回变换后的 HTML/文本
pub fn run_html_js(script: &str, html: &str, js_lib: &str, base_url: &str) -> Result<String, String> {
    run_with_result(script, html, js_lib, base_url)
}

/// 提取 `<js>...</js>` 内脚本
pub fn extract_js_block(rule: &str) -> Option<String> {
    let start = rule.find("<js>")?;
    let end = rule.find("</js>")?;
    if end <= start {
        return None;
    }
    Some(rule[start + 4..end].to_string())
}

/// 规则是否含 `<js>` 块
pub fn contains_js_block(rule: &str) -> bool {
    rule.contains("<js>") && rule.contains("</js>")
}

/// 提取 `<js>...</js>` 之后的 CSS/链式规则部分
pub fn css_suffix_after_js(rule: &str) -> &str {
    if let Some(end) = rule.find("</js>") {
        rule[end + 5..].trim()
    } else {
        rule.trim()
    }
}

fn json_escape(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn run_simple_js_transform() {
        let out = run_with_result("result + '!'", "hello", "", "").unwrap();
        assert_eq!(out, "hello!");
    }

    #[test]
    fn run_jsoup_parse() {
        let script = r#"
var html = String(result);
var doc = Packages.org.jsoup.Jsoup.parse(html);
var a = doc.selectFirst('a');
a ? a.text() : '';
"#;
        let out = run_html_js(script, "<a href='/1'>书名</a>", "", "").unwrap();
        assert_eq!(out, "书名");
    }

    #[test]
    fn run_jsoup_select_id() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('#nr');
el ? el.text() : '';
"#;
        let html = r#"<article id="nr">正文内容</article>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert_eq!(out, "正文内容");
    }

    #[test]
    fn run_jsoup_select_tag_id() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('article#nr');
el ? el.text() : '';
"#;
        let html = r#"<div><article id="nr">第一章</article></div>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert_eq!(out, "第一章");
    }

    #[test]
    fn run_jsoup_select_attr_equals() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('[id=nr]');
el ? el.text() : '';
"#;
        let html = r#"<article id="nr">属性选择</article>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert_eq!(out, "属性选择");
    }

    #[test]
    fn run_jsoup_html_method() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('article#nr');
el ? el.html() : '';
"#;
        let html = r#"<article id="nr"><p>段落</p></article>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert!(out.contains("<p>段落</p>"), "html() 应含 inner HTML: {out}");
    }

    #[test]
    fn run_jsoup_7565_content_script() {
        let script = r#"
var html = String(result);
var doc = Packages.org.jsoup.Jsoup.parse(html);
var nr = doc.selectFirst('article#nr');
var lines = [];
if (nr) {
    var rawHtml = String(nr.html());
    rawHtml = rawHtml.replace(/<br\s*\/?>/gi, '\n');
    var parts = rawHtml.split('\n');
    for (var i = 0; i < parts.length; i++) {
        var line = parts[i].replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').replace(/\u00a0/g, ' ').trim();
        if (line) {
            lines.push(line);
        }
    }
}
lines.join('\n');
"#;
        let html = r#"
<html><body>
<article id="nr">
<p>第一章 开端</p><br/>
<p>这是测试正文段落，字数需要足够多以验证清洗逻辑正常工作。</p>
<p>第二段继续补充内容，确保 join 后超过一百个字符。</p>
</article>
</body></html>
"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert!(out.len() > 100, "7565 脚本输出过短: {} chars", out.len());
        assert!(out.contains("测试正文"), "应含正文: {out}");
    }

    /// 笔书网移动站：正文是文本节点与 `<br/>` 交错；若 html() 先拼全部 text 再拼子节点，
    /// 整章会落在一行并被「本章未完.*继续阅读」过滤成空。
    #[test]
    fn run_jsoup_preserves_br_text_order_for_7565_filter() {
        let script = r#"
var html = String(result);
var doc = Packages.org.jsoup.Jsoup.parse(html);
var nr = doc.selectFirst('article#nr');
var lines = [];
if (nr) {
    var rawHtml = String(nr.html());
    rawHtml = rawHtml.replace(/<br\s*\/?>/gi, '\n');
    var parts = rawHtml.split('\n');
    for (var i = 0; i < parts.length; i++) {
        var line = parts[i].replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').replace(/\u00a0/g, ' ').trim();
        if (line) {
            if (/最新网址|m\.biqukun|本章未完.*继续阅读/.test(line)) continue;
            lines.push(line);
        }
    }
    if (lines.length > 0 && /^第\d+章/.test(lines[0])) {
        lines.shift();
    }
}
lines.join('\n');
"#;
        let html = r#"
<html><body>
<article id="nr">&nbsp;&nbsp;&nbsp;&nbsp;第5章 标题 (第1/3页)<br /><br />旁白：这是正文第一段足够长。<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;这是正文第二段，继续补充内容避免过短。<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;本章未完，请翻下一页继续阅读。</article>
</body></html>
"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert!(out.contains("正文第一段"), "应保留正文: {out}");
        assert!(out.contains("正文第二段"), "应保留分段: {out}");
        assert!(!out.contains("本章未完"), "应过滤未完提示: {out}");
        assert!(!out.contains("第5章"), "应去掉章名行: {out}");
    }

    #[test]
    fn run_jsoup_html_is_inner_with_ordered_br() {
        let script = r#"
var doc = Packages.org.jsoup.Jsoup.parse(String(result));
var el = doc.selectFirst('article#nr');
el ? el.html() : '';
"#;
        let html = r#"<article id="nr">甲<br />乙</article>"#;
        let out = run_html_js(script, html, "", "").unwrap();
        assert!(!out.contains("<article"), "html() 应为 inner: {out}");
        assert!(
            out.contains("甲") && out.contains("乙") && out.find("甲").unwrap() < out.find("乙").unwrap(),
            "文本与 br 须保序: {out}"
        );
        assert!(
            out.find("甲").unwrap() < out.to_lowercase().find("br").unwrap()
                && out.to_lowercase().find("br").unwrap() < out.find("乙").unwrap(),
            "顺序应为 甲 / br / 乙: {out}"
        );
    }

    /// 可乐小说 searchUrl：AES-256-CBC + encryptBase64（Hutool/Legado java.createSymmetricCrypto）
    #[test]
    fn run_create_symmetric_crypto_aes_cbc_encrypt_base64() {
        let script = r#"
var keyStr='lzxHpH8PLGXcrCIQ';
var key32=keyStr;
while(key32.length < 32){key32 += String.fromCharCode(0);}
var crypto=java.createSymmetricCrypto('AES/CBC/PKCS5Padding',key32,keyStr);
crypto.encryptBase64(key);
"#;
        let out = run_search_js(script, "重生之", "", "https://www.rrssk.com/", 1).unwrap();
        assert_eq!(out, "breUSzu0dAfgrP33wtpsvg==");
    }

    #[test]
    fn run_kele_search_url_template_js() {
        let template = r#"<js>var keyStr='lzxHpH8PLGXcrCIQ';var key32=keyStr;while(key32.length < 32){key32 += String.fromCharCode(0);}var crypto=java.createSymmetricCrypto('AES/CBC/PKCS5Padding',key32,keyStr);var enc=crypto.encryptBase64(key);var url='https://www.rrssk.com/k-'+enc+'.html';if(page>1)url='https://www.rrssk.com/k-'+enc+'-'+page+'.html';url</js>"#;
        let out = run_url_template_js(template, "重生之", "", "https://www.rrssk.com/", 1).unwrap();
        assert_eq!(
            out,
            "https://www.rrssk.com/k-breUSzu0dAfgrP33wtpsvg==.html"
        );
        let out2 = run_url_template_js(template, "重生之", "", "https://www.rrssk.com/", 2).unwrap();
        assert_eq!(
            out2,
            "https://www.rrssk.com/k-breUSzu0dAfgrP33wtpsvg==-2.html"
        );
    }

    #[test]
    fn java_ajax_binding_registered() {
        let out = run_eval_script(
            "typeof java.ajax === 'function' && typeof __legado_java_ajax === 'function' ? 'ok' : 'no'",
            "",
            "https://www.kelexs.com/",
        )
        .unwrap();
        assert_eq!(out, "ok");
    }

    #[test]
    fn java_ajax_ssrf_returns_empty() {
        let out = run_eval_script("java.ajax('http://127.0.0.1/')", "", "").unwrap();
        assert_eq!(out, "");
    }

    #[test]
    fn java_ajax_accepts_analyze_url_post_shape() {
        // 不发起真实外网：非法主机应被 SSRF 拦截并返回空串；同时验证 AnalyzeUrl 解析不 panic
        let out = run_eval_script(
            r#"java.ajax('http://127.0.0.1/login,{"method":"POST","body":"a=1","headers":{"X-Test":"1"}}')"#,
            "",
            "https://example.com/",
        )
        .unwrap();
        assert_eq!(out, "");
    }

    #[test]
    fn set_ajax_ctx_exposed() {
        let out = run_eval_script(
            "typeof __legado_set_ajax_ctx === 'function' ? 'ok' : 'no'",
            "",
            "",
        )
        .unwrap();
        assert_eq!(out, "ok");
    }

    #[test]
    fn shared_cache_across_js_runtimes() {
        let _ = reset_cache();
        let put = run_with_result(
            "cache.put('kelexs_key','abc123',86400); cache.get('kelexs_key')",
            "",
            "",
            "https://www.kelexs.com/",
        )
        .unwrap();
        assert_eq!(put, "abc123");
        // 新 Runtime 仍能读到
        let got = run_with_result("cache.get('kelexs_key')", "", "", "https://www.kelexs.com/")
            .unwrap();
        assert_eq!(got, "abc123");
        let _ = reset_cache();
        assert_eq!(
            run_with_result("cache.get('kelexs_key')", "", "", "").unwrap(),
            ""
        );
    }
}
