// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_database_error`

/// 导出数据库备份 JSON（书架/书源/章节/规则/阅读记录）
String exportBackup() => LegadoEngine.instance.api.crateApiBackupExportBackup();

/// 从备份 JSON 恢复；replace=true 时清空后导入
void restoreBackup({required String json, required bool replace}) =>
    LegadoEngine.instance.api.crateApiBackupRestoreBackup(
      json: json,
      replace: replace,
    );
