// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取书籍详情
Future<BookInfoItem> getBookInfo({
  required String sourceJson,
  required String bookUrl,
}) => LegadoEngine.instance.api.crateApiBookInfoGetBookInfo(
  sourceJson: sourceJson,
  bookUrl: bookUrl,
);
