// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取章节正文
Future<String> getContent({
  required String sourceJson,
  required String chapterUrl,
}) => LegadoEngine.instance.api.crateApiContentGetContent(
  sourceJson: sourceJson,
  chapterUrl: chapterUrl,
);
