// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化数据库（与 Flutter `legado.db` 同路径）
void dbInit({required String path}) =>
    LegadoEngine.instance.api.crateApiDbDbInit(path: path);

int dbSchemaVersion() => LegadoEngine.instance.api.crateApiDbDbSchemaVersion();

String dbProbeLegacyRoomDatabase({required String path}) =>
    LegadoEngine.instance.api.crateApiDbDbProbeLegacyRoomDatabase(path: path);

String dbImportLegacyRoomDatabase({
  required String path,
  String? backupPath,
  required bool replace,
}) => LegadoEngine.instance.api.crateApiDbDbImportLegacyRoomDatabase(
  path: path,
  backupPath: backupPath,
  replace: replace,
);

void dbInsertBook({required String bookJson}) =>
    LegadoEngine.instance.api.crateApiDbDbInsertBook(bookJson: bookJson);

List<String> dbGetBooks() => LegadoEngine.instance.api.crateApiDbDbGetBooks();

void dbDeleteBook({required String bookId}) =>
    LegadoEngine.instance.api.crateApiDbDbDeleteBook(bookId: bookId);

void dbUpdateBookProgress({
  required String bookId,
  required double progress,
  String? chapter,
  required int pageIndex,
}) => LegadoEngine.instance.api.crateApiDbDbUpdateBookProgress(
  bookId: bookId,
  progress: progress,
  chapter: chapter,
  pageIndex: pageIndex,
);

void dbUpdateBookCover({required String bookId, required String coverUrl}) =>
    LegadoEngine.instance.api.crateApiDbDbUpdateBookCover(
      bookId: bookId,
      coverUrl: coverUrl,
    );

void dbUpdateBookGroup({required String bookId, required String group}) =>
    LegadoEngine.instance.api.crateApiDbDbUpdateBookGroup(
      bookId: bookId,
      group: group,
    );

void dbUpsertSource({required String sourceJson}) =>
    LegadoEngine.instance.api.crateApiDbDbUpsertSource(sourceJson: sourceJson);

List<String> dbGetSources({required bool enabledOnly}) =>
    LegadoEngine.instance.api.crateApiDbDbGetSources(enabledOnly: enabledOnly);

void dbToggleSource({required String url, required bool enabled}) =>
    LegadoEngine.instance.api.crateApiDbDbToggleSource(
      url: url,
      enabled: enabled,
    );

void dbDeleteSource({required String url}) =>
    LegadoEngine.instance.api.crateApiDbDbDeleteSource(url: url);

void dbInsertChapters({required String chaptersJson}) => LegadoEngine
    .instance
    .api
    .crateApiDbDbInsertChapters(chaptersJson: chaptersJson);

List<String> dbGetChapters({required String bookId}) =>
    LegadoEngine.instance.api.crateApiDbDbGetChapters(bookId: bookId);

String? dbGetChapterContent({required String chapterId}) => LegadoEngine
    .instance
    .api
    .crateApiDbDbGetChapterContent(chapterId: chapterId);

void dbSaveChapterContent({
  required String chapterId,
  required String content,
}) => LegadoEngine.instance.api.crateApiDbDbSaveChapterContent(
  chapterId: chapterId,
  content: content,
);

void dbUpsertReplaceRule({required String ruleJson}) =>
    LegadoEngine.instance.api.crateApiDbDbUpsertReplaceRule(ruleJson: ruleJson);

List<String> dbGetReplaceRules() =>
    LegadoEngine.instance.api.crateApiDbDbGetReplaceRules();

void dbToggleReplaceRule({required String id, required bool enabled}) =>
    LegadoEngine.instance.api.crateApiDbDbToggleReplaceRule(
      id: id,
      enabled: enabled,
    );

void dbDeleteReplaceRule({required String id}) =>
    LegadoEngine.instance.api.crateApiDbDbDeleteReplaceRule(id: id);

void dbClearReplaceRules() =>
    LegadoEngine.instance.api.crateApiDbDbClearReplaceRules();
