// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `preview_body`, `push_step`, `search_items_to_debug`

/// 分步调试搜索
Future<DebugResult> debugSearch({
  required String sourceJson,
  required String keyword,
}) => LegadoEngine.instance.api.crateApiDebugDebugSearch(
  sourceJson: sourceJson,
  keyword: keyword,
);

/// 分步调试目录
Future<DebugResult> debugToc({
  required String sourceJson,
  required String bookUrl,
}) => LegadoEngine.instance.api.crateApiDebugDebugToc(
  sourceJson: sourceJson,
  bookUrl: bookUrl,
);
