// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_legacy`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

@freezed
sealed class AppError with _$AppError implements FrbException {
  const AppError._();

  const factory AppError.network(String field0) = AppError_Network;
  const factory AppError.parse(String field0) = AppError_Parse;
  const factory AppError.database(String field0) = AppError_Database;
  const factory AppError.jsExecution(String field0) = AppError_JsExecution;
  const factory AppError.validation(String field0) = AppError_Validation;
  const factory AppError.unsupported(String field0) = AppError_Unsupported;
  const factory AppError.cancelled(String field0) = AppError_Cancelled;
  const factory AppError.unknown(String field0) = AppError_Unknown;
}
