// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 发现页 / 分类页
Future<List<SearchItem>> explore({
  required String sourceJson,
  required String exploreUrl,
  required int page,
}) => LegadoEngine.instance.api.crateApiExploreExplore(
  sourceJson: sourceJson,
  exploreUrl: exploreUrl,
  page: page,
);
