// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attr_value`, `chapter_title_from_html`, `collapse_blank_lines`, `html_to_plain`, `is_safe_path_segment`, `is_supported_book_path`, `is_windows_drive_segment`, `join_zip_path`, `opf_path_from_container`, `parse_epub_legacy`, `parse_opf`, `parse_remote_archive_book_files_with_limits`, `parse_remote_archive_book_files`, `path_dir`, `read_zip_entry`, `safe_zip_relative_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OpfMeta`

/// TXT 分章 — 匹配常见章节标题
Future<List<LocalChapterItem>> parseTxtChapters({required String content}) =>
    LegadoEngine.instance.api.crateApiLocalBookParseTxtChapters(
      content: content,
    );

/// EPUB 解析 — zip → OPF spine → 章节正文
Future<LocalBookInfo> parseEpub({required List<int> data}) =>
    LegadoEngine.instance.api.crateApiLocalBookParseEpub(data: data);
