// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 应用代理 / DNS 配置
void setNetworkConfig({
  required bool proxyEnabled,
  required String proxyType,
  required String proxyHost,
  required int proxyPort,
  required String proxyUsername,
  required String proxyPassword,
  required String dnsServers,
}) => LegadoEngine.instance.api.crateApiNetworkSetNetworkConfig(
  proxyEnabled: proxyEnabled,
  proxyType: proxyType,
  proxyHost: proxyHost,
  proxyPort: proxyPort,
  proxyUsername: proxyUsername,
  proxyPassword: proxyPassword,
  dnsServers: dnsServers,
);

/// 清空 HTTP Cookie 与 JS 内存缓存
void clearEngineCache() =>
    LegadoEngine.instance.api.crateApiNetworkClearEngineCache();

/// 开启一次 debug HTTP 请求轨迹采集。
void startHttpRequestTrace() =>
    LegadoEngine.instance.api.crateApiNetworkStartHttpRequestTrace();

/// 停止并取出 debug HTTP 请求轨迹 JSON。
String drainHttpRequestTrace() =>
    LegadoEngine.instance.api.crateApiNetworkDrainHttpRequestTrace();

/// 当前网络配置
NetworkConfigDto getNetworkConfig() =>
    LegadoEngine.instance.api.crateApiNetworkGetNetworkConfig();

/// 通过统一 Rust HTTP 客户端抓取公开文本资源。
///
/// `user_agent` 为空时使用引擎默认值；传入 `null` 对齐规则订阅
/// `#requestWithoutUA` 的既有请求语义。
Future<String> fetchPublicText({
  required String url,
  required String userAgent,
}) => LegadoEngine.instance.api.crateApiNetworkFetchPublicText(
  url: url,
  userAgent: userAgent,
);

/// 发送应用服务 HTTP 请求。`allow_private_network` 仅供用户显式配置的本地服务使用。
Future<ApplicationHttpResponseDto> sendApplicationHttpRequest({
  required String url,
  required String method,
  required Map<String, String> headers,
  String? body,
  required int timeoutSeconds,
  required bool allowPrivateNetwork,
}) => LegadoEngine.instance.api.crateApiNetworkSendApplicationHttpRequest(
  url: url,
  method: method,
  headers: headers,
  body: body,
  timeoutSeconds: timeoutSeconds,
  allowPrivateNetwork: allowPrivateNetwork,
);

class ApplicationHttpResponseDto {
  final int statusCode;
  final String body;

  const ApplicationHttpResponseDto({
    required this.statusCode,
    required this.body,
  });

  @override
  int get hashCode => statusCode.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplicationHttpResponseDto &&
          runtimeType == other.runtimeType &&
          statusCode == other.statusCode &&
          body == other.body;
}

/// 网络配置 DTO
class NetworkConfigDto {
  final bool proxyEnabled;
  final String proxyType;
  final String proxyHost;
  final int proxyPort;
  final String proxyUsername;
  final String proxyPassword;
  final String dnsServers;

  const NetworkConfigDto({
    required this.proxyEnabled,
    required this.proxyType,
    required this.proxyHost,
    required this.proxyPort,
    required this.proxyUsername,
    required this.proxyPassword,
    required this.dnsServers,
  });

  @override
  int get hashCode =>
      proxyEnabled.hashCode ^
      proxyType.hashCode ^
      proxyHost.hashCode ^
      proxyPort.hashCode ^
      proxyUsername.hashCode ^
      proxyPassword.hashCode ^
      dnsServers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkConfigDto &&
          runtimeType == other.runtimeType &&
          proxyEnabled == other.proxyEnabled &&
          proxyType == other.proxyType &&
          proxyHost == other.proxyHost &&
          proxyPort == other.proxyPort &&
          proxyUsername == other.proxyUsername &&
          proxyPassword == other.proxyPassword &&
          dnsServers == other.dnsServers;
}
