// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `explore_enabled`, `first_explore_category_url`, `pick_book`, `push_err`

/// 校验书源：搜索 → 发现（可选）→ 目录 → 正文
Future<SourceValidation> validateSource({
  required String sourceJson,
  required String keyword,
}) => LegadoEngine.instance.api.crateApiValidateValidateSource(
  sourceJson: sourceJson,
  keyword: keyword,
);
