// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_items`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 列出 WebDAV 目录
Future<List<WebDavEntry>> webdavList({
  required String url,
  required String username,
  required String password,
  required String path,
}) => LegadoEngine.instance.api.crateApiWebdavWebdavList(
  url: url,
  username: username,
  password: password,
  path: path,
);

/// 验证 WebDAV 目录访问权限
Future<void> webdavCheck({
  required String url,
  required String username,
  required String password,
  required String path,
}) => LegadoEngine.instance.api.crateApiWebdavWebdavCheck(
  url: url,
  username: username,
  password: password,
  path: path,
);

/// 确保 WebDAV 目录存在
Future<void> webdavEnsureDir({
  required String url,
  required String username,
  required String password,
  required String path,
}) => LegadoEngine.instance.api.crateApiWebdavWebdavEnsureDir(
  url: url,
  username: username,
  password: password,
  path: path,
);

/// 上传文件到 WebDAV
Future<void> webdavUpload({
  required String url,
  required String username,
  required String password,
  required String remotePath,
  required List<int> data,
}) => LegadoEngine.instance.api.crateApiWebdavWebdavUpload(
  url: url,
  username: username,
  password: password,
  remotePath: remotePath,
  data: data,
);

/// 从 WebDAV 下载文件
Future<Uint8List> webdavDownload({
  required String url,
  required String username,
  required String password,
  required String remotePath,
}) => LegadoEngine.instance.api.crateApiWebdavWebdavDownload(
  url: url,
  username: username,
  password: password,
  remotePath: remotePath,
);

/// 删除 WebDAV 文件
Future<void> webdavDelete({
  required String url,
  required String username,
  required String password,
  required String remotePath,
}) => LegadoEngine.instance.api.crateApiWebdavWebdavDelete(
  url: url,
  username: username,
  password: password,
  remotePath: remotePath,
);

/// 重命名 WebDAV 文件
Future<void> webdavMove({
  required String url,
  required String username,
  required String password,
  required String remotePath,
  required String destinationPath,
}) => LegadoEngine.instance.api.crateApiWebdavWebdavMove(
  url: url,
  username: username,
  password: password,
  remotePath: remotePath,
  destinationPath: destinationPath,
);

/// WebDAV 文件条目
class WebDavEntry {
  final String name;
  final String path;
  final bool isDir;
  final int size;
  final PlatformInt64 lastModified;

  const WebDavEntry({
    required this.name,
    required this.path,
    required this.isDir,
    required this.size,
    required this.lastModified,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          size == other.size &&
          lastModified == other.lastModified;
}
